### ISSUE TITLE
Courtesy notification

### ISSUE THREAD

**Issue by pdehaye** [DP-3T/documents#1]
Thank you for submitting this publicly. 

I have been or have attempted to be in contact with some of the authors of the privacy framework presented here over the last 14 days (whom I highly respect, but didn't necessarily know were authors of this framework). 

Given that up until two hours ago:
* the importance of those matters, 
* the announced timeline for rollout of code and apps, 
* the content displayed on the site and the communication made available by the PEPP-PT project (for instance the lack of individual accountability behind the chosen privacy framework), 

I felt it was important to signal to the privacy community potential issues around the protocol, as I could piece it together from public claims, the website, conversations with some members of the PEPP-PT team, and others. 

For this reason, I have given a talk _a mere hour before you published this framework_ to an online seminar of the OpenRightsGroup on the failures of PEPP-PT as far as I could tell from where I was. My goal was to be able to act as an exterior grain of salt in nudging what must be complex internal politics in the right direction, at the risk of making a fool of myself. 

The video of my talk should hit Youtube within a couple days. I am therefore leaving a comment here as a courtesy, so you can update those who might see my video and then ask you what you make of my presentation. 

I see and welcome that you are mentioning the issue of the _Breyer_ jurisprudence in your assessment (~~as I mentioned to some of you was relevant, again not knowing you were involved~~). I am looking forward to reading the exact details, which will matter of course, and that I have not been able myself to reflect on.

~~In the unlikely event that my private comments have led to an improvement to the paper, I would appreciate mention of this in your documents.~~ (EDIT 2020.04.06 here and above. For more, see below)

In the more likely event that you decide to change the wording of some claims on your website in light of the documents presented here, I would suggest for transparency tracking the exact changes made in the content of the site.

**Comment by pdehaye** [comment]
This is a link to the talk: 
https://twitter.com/OpenRightsGroup/status/1247143535566077953?s=20

**Comment by pdehaye** [comment]
Referring to the strikethrough above: 

I wish to apologize to those whose private conversation I have betrayed.

Additionally, I have mischaracterized my own private comments since they didn't contain any mention of the _Breyer_ case. I therefore added insult to injury, and wish to apologize for this as well.

**Comment by kennypaterson** [comment]
Thanks for your comment. In case there is any misconception: DP-3T is one possible way that PEPP-PT could be built. We, the people named on the DP-3T proposal, have recommended, and continue to recommend, the DP-3T approach to the PEPP-PT project.
