### ISSUE TITLE
Design 2 - Excelent for performance - my compliments

### ISSUE THREAD

**Issue by dirkx** [DP-3T/documents#102]
My compliments for performance on design two; very easy to handle many 100't of thousands of entries on an old mobile phone within second(s). And with very modest serialised size filters.

 (trivial case without backend/frontend test https://gist.github.com/dirkx/d42c7553bbf3f601725d972fb76e0dd3)

PS: Apologies for using a ticket - but no other means of contacting you lot :)

**Comment by lbarman** [comment]
Hi @dirkx, thanks a lot! the team saw it :)
Closing to try reducing the number of open issues...
