### ISSUE TITLE
smartphone automaticaly contacts authorities? ---> no privacy 

### ISSUE THREAD

**Issue by Alain2019** [DP-3T/documents#106]
p10 whitepaper :
"When the smartphone determines its owner has a high risk score, the smartphone contacts
its local health authority as if it was not roaming."

I thought that the user was in control.  Privacy goes down the drain here.

**Comment by wouterl** [comment]
Great catch @Alain2019! I could have sworn we caught them all. Fixing this in the next release of the white paper. It should have said that the smartphone notifies the owner (e.g., using a notification or something) as before. No data is sent anywhere.
