### ISSUE TITLE
Title of P6 in FAQ

### ISSUE THREAD

**Issue by enriconardelli** [DP-3T/documents#107]
The actual title of P6 is «Why do infected people upload a seed (which enables recreating EphIDs) instead of their individual EphIDs?» but what you discuss is, I guess, the fact the backend broadcasts the seeds of infected persons.

In fact, in itself uploading the seed does not give away anonymity of the infected person, given this seed was randomly generated when the app was installed. There is instead a problem in the fact that the backend server brodcasts this seed instead of the derived EphIDs. The answer given in the FAQ discuss, I think, this issue using performances argument, which I find reasonable, in principle. But given privacy is involved here, I remain convinced the protocol SHOULD NOT broadcast the seed but only the the EphIDs.

**Comment by jasisz** [comment]
@enriconardelli They've added the second design to the original docs. It is basically what you describe, but EphIDs are distributed in the form of a cuckoo filter.

**Comment by enriconardelli** [comment]
@Jasisz, yes, but I'm not discussing a weakness of design 1. My point is that the answer to FAQ P6 refers to something different from P6 title. The title says "upload" while in the answer discuss "So smartphones would need to download at least 2 orders of magnitude more (e.g., for 30k infected a day: from around 1 MB to 230 MB per day)."

**Comment by mex2meou** [comment]
Hi @enriconardelli, thanks for raising this issue!

We are discussing what information is 'uploaded' by infected users. Naturally, this also affects the amount of information that all other users need to 'download' from the backend server -- which is also part of our answer to this question.

Does this make sense?

**Comment by s-chtl** [comment]
Closing this issue for now
