### ISSUE TITLE
Public domain comic by Nicky Case explaining DP-3T

### ISSUE THREAD

**Issue by kkoenen** [DP-3T/documents#108]
To include in this repository?

![IMG_20200409_195941](https://user-images.githubusercontent.com/1116248/78928717-6588aa00-7aa1-11ea-8565-fada841d1a79.jpg)
![IMG_20200409_195944](https://user-images.githubusercontent.com/1116248/78928736-6b7e8b00-7aa1-11ea-8ac6-f4907cce3aa5.jpg)
![IMG_20200409_200003](https://user-images.githubusercontent.com/1116248/78928782-7f29f180-7aa1-11ea-8f89-04838c821283.jpg)
![IMG_20200409_200007](https://user-images.githubusercontent.com/1116248/78928787-85b86900-7aa1-11ea-8cf9-f3c53a5fa339.jpg)
![IMG_20200409_200012](https://user-images.githubusercontent.com/1116248/78928804-8bae4a00-7aa1-11ea-9c49-33ab5ab5a8d2.jpg)
![IMG_20200409_200017](https://user-images.githubusercontent.com/1116248/78928823-92d55800-7aa1-11ea-9cd7-1726e6ef00b1.jpg)
![IMG_20200409_200020](https://user-images.githubusercontent.com/1116248/78928853-a254a100-7aa1-11ea-909f-1a6a10c40e62.jpg)
![IMG_20200409_200024](https://user-images.githubusercontent.com/1116248/78928866-aa144580-7aa1-11ea-919d-847b213e9a00.jpg)
![IMG_20200409_200028](https://user-images.githubusercontent.com/1116248/78928883-b26c8080-7aa1-11ea-9170-0da0ef152b90.jpg)
![IMG_20200409_200031](https://user-images.githubusercontent.com/1116248/78928898-bb5d5200-7aa1-11ea-9844-d973c4e2f9b4.jpg)
![IMG_20200409_200034](https://user-images.githubusercontent.com/1116248/78928907-c1ebc980-7aa1-11ea-9ae8-93595fe3b10d.jpg)
![IMG_20200409_200037](https://user-images.githubusercontent.com/1116248/78928925-c9ab6e00-7aa1-11ea-88d5-c14a0f9e1bf5.jpg)
![IMG_20200409_200041](https://user-images.githubusercontent.com/1116248/78928947-d4660300-7aa1-11ea-8ded-0180a356a809.jpg)
![IMG_20200409_200044](https://user-images.githubusercontent.com/1116248/78928968-d9c34d80-7aa1-11ea-8605-97fbf7d56031.jpg)
![IMG_20200409_200047](https://user-images.githubusercontent.com/1116248/78928977-dd56d480-7aa1-11ea-9170-c5f811ae0213.jpg)
![IMG_20200409_200049](https://user-images.githubusercontent.com/1116248/78928988-e051c500-7aa1-11ea-8d43-477bccb898cb.jpg)
![IMG_20200409_200053](https://user-images.githubusercontent.com/1116248/78929001-e3e54c00-7aa1-11ea-967e-819e8f26b669.jpg)
![IMG_20200409_200056](https://user-images.githubusercontent.com/1116248/78929006-e6e03c80-7aa1-11ea-90ea-2e480f0f6c0a.jpg)

**Comment by veale** [comment]
Thanks, this is now done (was being pushed simultaneously). We strongly welcome those who wish to translate this into other languages, see README in [the relevant folder](https://github.com/DP-3T/documents/tree/master/public%20engagement/cartoon)..
