### ISSUE TITLE
Design 2; seed rather than H(TRUNK128(seed)||t)

### ISSUE THREAD

**Issue by dirkx** [DP-3T/documents#109]
May be good to explain more clearly why it is needed for the invected user to sent (t,seed) pairs as opposed to the observable ``H(TRUNK128(seed)||t)'' -- as I assume this is to prevent stuffing / `proof' that the phone submitting the seeds is the one which once was able to send those EphIDs.

**Comment by lbarman** [comment]
Hi @dirkx, you're correct. I've added to the edits of the whitepaper, it will appear soon. Thanks !
