### ISSUE TITLE
Fix claims on the PEPP-PT website to match what is announced here

### ISSUE THREAD

**Issue by pdehaye** [DP-3T/documents#11]
One of the authors of this set of papers has [publicly referred to these documents as relevant to PEPP-PT](https://twitter.com/marcelsalathe/status/1246127370744061966?s=20). 

However the [PEPP-PT website](http://www.pepp-pt.org/) states (among other things):

> Our privacy core: anything we provide is based on voluntary participation, provides anonymity, does not use personal data nor geolocation information, operates in full compliance with GDPR, and has been certified and tested by security professionals.

This does not quite square with the assessment made in the documents published today. For instance the Breyer discussion is - even without making changes due to #9 or other changes suggested by others - not quite as categorical in claiming that the centralizing entity "does not use personal data" and therefore that it magically "operates in full compliance with GDPR". 

This protocol will encourage data sharing between governments at a time when:
* some European governments are diverging away from their commitments to human rights, and 
* some are deploying very creative approaches to weakening GDPR by somewhat weaponizing precisely the jurisprudence out of _Breyer_ (see [my testimony in the UK Parliament on the topic, at the end](http://data.parliament.uk/WrittenEvidence/CommitteeEvidence.svc/EvidenceDocument/Digital,%20Culture,%20Media%20and%20Sport/Disinformation%20and%20%E2%80%98fake%20news%E2%80%99/Written/80117.html))

In addition, as acknowledged by the authors, this protocol could be repurposed for vastly different means down the line, and overconfident "no personal data" claims could give a techno/legal mandate to circumvent usual GDPR protections. 

As a consequence, the legal language has to be extremely sharp in all communications, already now.

**Comment by pdehaye** [comment]
See also #28

**Comment by pdehaye** [comment]
I guess this one is on hold, given the [clarification most recently posted](https://github.com/DP-3T/documents/issues/28#issuecomment-609499957).

**Comment by cascremers** [comment]
We do not control the PEPP-PT website. Suggestions for changes to their website are perhaps best put to their contact address (an email address is listed there).

Closing this issue, since it is not within our power to make the suggested changes.
