### ISSUE TITLE
Handling of false positives?

### ISSUE THREAD

**Issue by ecdr** [DP-3T/documents#110]
How does the protocol handle uncertainty in the test results?

How will the protocol handle false positives?  (e.g., wrong person given positive test result)
Is there a way to retract a positive?  How do clients verify the retraction?

For a presumptive positive (e.g., showed symptoms, etc., but testing not performed - maybe they died before testing, or test was not available, or takes a long time to get the test result), I presume the code provided by the health care authority will encode information about the confidence level of the result.

**Comment by heroichornet** [comment]
Worst case is people isolate that don't have to. False positives should be treated like true positives. False negatives are more of an issue. If there is a statistically significant likelihood of a wrong test result (which I don't think there is) then people should be informed to be precautions when someone has tested negative but is showing symptoms or has been in contact with an infected individual.

**Comment by lbarman** [comment]
Hi @ecdr, sorry for the delay, this got buried under a pile of other issues sadly. (we can thank @heroichornet for bumping it)

The app doesn't give "positives" as in "you're sick", its positive message is "you may be at risk". We don't diagnose people; the point is to put them in touch with the health services for whatever procedure (e.g., preliminary diagnostic over phone)

> I  presume the code provided by the health care authority will encode information about the confidence level of the result.

No; the purpose of this code is purely authorization to upload. Only the app might itself (locally) give a confidence level / risk level to the user.

The false negative are indeed an issue, this will depend on how well the Bluetooth contact-tracing works.

Would this answer the question ?
