### ISSUE TITLE
Design 2: when patients are infected, they upload....

### ISSUE THREAD

**Issue by sc-fx** [DP-3T/documents#114]
uploading should be when patients are infected or not, otherwise they declare themselves infected not only to their contacts but also to upload server S.

At any time, A should be able to upload x=f(ephIDs emitted by A,ephIDs received by A, C)  to S, with C either certifying that A is infected, or C random, in such a way that 
:
- the parameters of f can not be retrieved from x
- the source B of an ephID received by A can recognize itself from x if and only if A is infected, 
- B can not identify A from x

**Comment by lbarman** [comment]
hi @sc-fx; thanks! 

> uploading should be when patients are infected or not, otherwise they declare themselves infected not only to their contacts but also to upload server S.

Non-infected users should also upload dummy data (like we describe for epidemiologists), this will be included in a future release of the whitepaper.

>x=f(ephIDs emitted by A,ephIDs received by A, C)
In this design, we explicitely avoided uploading graph data ("the ephIDs received by A") as this is hard to anonymize and give the backend a lot of information (see our FAQ, P1 IIRC). This would not be a concern if indeed the parameters are not recoverable from f, but how would `f` look like in real life ?

**Comment by sc-fx** [comment]
Hi Ludovic,

Actually you are right, my remark concerns two problems:
1) a user A contacts the backend S only when it is infected (and then an eavesdropper on S can identify the infected users)
2) the backend S itself knows all the infected user (and it should not: only the users B should know that they have been in contact with an (unidentified) infected user)

Problem 1 is easy to address, since it suffices that A has the ability to contact S even when it is not  infected.

Problem 2 is more tricky. I believe a cryptologist should be able to address it easily (I am not a cryptologist). A basic solution is as follows. At time t, user B broadcasts SK^B_t. Assume SK^B_t to be a public cryptographic key. When A is tested positive for Corona, the doctor D_A of A provides a certificate (cryptographic meaning) C_D to A. The purpose of C_D is just to ensure that when A declares its infection, it is a true infection. C_D depends only of D, and not of A, so that A can not be retrieved from C_D. Then A sends m=SK^B_t*C_D to S. Here SK^B_t*C_D means that C_D is encrypted using SK^B_t. S is not able to decrypt m. B uploads m, is the only one able to retrieive C_D from m, and checks that C_D is a valid certificate. B has been in contact with an (anonymous) infected user if and only if C_D is a valid certificate.

**Comment by lbarman** [comment]
I see; in fact I believe our system also addresses this, to be sure, let me ask.
> the backend S itself knows all the infected user (and it should not: only the users B should know that they have been in contact with an (unidentified) infected user)

How so ? In our design the backend only receives random numbers; to follow your example, `A sends m=seed to S` (whereas you want to do `A sends=Encryption_PK(something) to S`). So if I get it correctly, the backend sees the same metadata in our proposals and yours.

**Comment by sc-fx** [comment]
But the backend S receives those random numbers from A when A is infected, so S knows that A is infected.

If I follow "Decentralized Privacy-Preserving Proximity Tracing" (Version of 12th April 2020), page 11 paragraphs -3, -2, -1, and Figure PT step 2, when A is infected, it sends (SK_t,t) to the backend S (I am sorry, I used the notation SK (in my draft of solution for Problem 2) for another purpose, which may lead to confusion). From this moment, S knows that A is infected. I may be missing something, but I can not see anything that prevents that. The first sentence of Paragraph -1 "The backend collects the pairs (SK_t,t) of infected patients and periodically sends them to all..." suggests that S knows the infected patients (and he should'nt).

**Comment by lbarman** [comment]
Sorry for the confusion, got it now.
To be precise, the backend knows "the infected patient" pseudonymously: he only sees a TCP packet coming from a certain IP containing a random number (the seed). (not like "John Smith is infected").
Anyway, so you suggest that non-infected also upload something (which the server can't differentiate) so that the server truly can't tell anything about infection/non-infection. When do you envision this upload to happen ? This seems hard to scale if done on a daily basis for instance.

**Comment by sc-fx** [comment]
> Anyway, so you suggest that non-infected also upload something (which the server can't differentiate) so that the server truly can't tell anything about infection/non-infection. When do you envision this upload to happen ? This seems hard to scale if done on a daily basis for instance.

Yes. The backend should not be able to tell anything about infection/non-infection. "When" for the upload of non-infected client has no importance: it is on a random basis. It suffices to observe that a client A uploads to backend server only 1 time when it is infected (so one time at most during all the lifetime of client A). If non-infected A uploads to S only 1 time during all its lifetime, then probability that S can say if A is infected is random: 1 over 2. Of course, if non infected A uploads more that 1 time during its lifetime (say, randomly, can be much less than every day), it is better.

**Comment by sc-fx** [comment]
> then probability that S can say if A is infected is random

if S is not able to decode the data received from A, of course.

**Comment by sc-fx** [comment]
> he only sees a TCP packet coming from a certain IP containing a random number (the seed).

In my opinion an IP address is an important leak with respect to anonymization.

**Comment by lbarman** [comment]
Hmm. I think I see. Would your proposal be equivalent to: non-infected randomly upload a random seed (if we consider our first design) ? Then the server sees seeds from infect/non-infected, with in the absence of collisions (= with high probability), this random seed will never match a real contact.
If so, why not, this needs to be studied in terms of scalability.

**Comment by sc-fx** [comment]
It is not strictly equivalent, since for instance in my proposal there is (theoretically) no risk of collision,
but what you are saying seems to be a nice and simple alternative (with the assumption that the server is not able to make the difference between the random "non-infected" seeds from the other ones). It must also be ensured that an infected client A can not send the same "true" seed twice, when the probability of sending twice the same "false" seed is 0, otherwise A reveals it is infected.

**Comment by sc-fx** [comment]
After reading "Analysis of DP3T between Scylla and Charybdis" by Vaudenay, 8th April, I realize that in my proposal the informations that enables B to know it has been in contact with an infected A does not contain any information about A; in particular B can not identify A even by "Nerd" or "Militia" attack (p10 of Vaudenay's document). From this point of view your proposal is not equivalent.

**Comment by lbarman** [comment]
I'm lost, sorry: what's the attack (do you have a simple example) ?

**Comment by sc-fx** [comment]
B has been in contact with infected A; it receives (SK_t,t) from the backend server, with (SK_t,t) used to generate some ephIDi that has been transmitted by A to B when they encountered.

Assumes B is a nerd: more than just collecting the ephID's, it associates to every ephID it collect some additional informations about the sender of the ephID (say for example, the physical bluetooth address of the sender of the ephID, but it can be anything else). With (SK_t,t), B is able to compute which ephID he received from the infected, and to associate to it the physical bluetooth address of A, which can be used to retrieve the identity of A (assuming B has the ability to retrieve the identity of A from its bluetooth physical address, which of course is not a triviality but also not to exclude).

**Comment by lbarman** [comment]
Thanks for your message.

Yes, this is a known attack which has been discussed at length in the issues and the FAQ.

I don't see yet how is A unable to identify B in your proposal ? Lemme write a generic attack: As "A", I create one account per 15min (that's 96 accounts). Every 15min I use a different account. When receiving a message "Account X is at-risk" I know which 15-min slot is in question and who I met during this slot. I can of course be more fine-grained. Our take is: the mere bit "you're at risk" or not, which all contact-tracing systems need to send, is sufficient to perform some de-anonymization.

**Comment by sc-fx** [comment]
I apologize for not seeing this attack was in the FAQ.

I agree with your generic attack, which also works at least with Design 1.

I meant that if a malicious user B keeps in memory for each ephID e the bluetooth address b (of user A) it was from, after B has received the (SK_t,t) of A and retrieve b, he can use an application that scans for b from now and checks if he meet A again (physically). With my proposal all that B knows is the public key k that he sent to A when they met (and, you are right, the time he sent k, which seems unavoidable and can be used for de-anonymisation): B can not use these information to check for another meeting with A.

Your generic attack can be used for de-anonymisation in the past (provided the attacker has sufficient informations, but is it really likely ?). What I meant is that de-anonymisation can also be done in the future; this can be done much more easily using design 1 (for a malicious user) than with my proposal.

**Comment by lbarman** [comment]
>I apologize for not seeing this attack was in the FAQ.

No worries!
> it was from, after B has received the (SK_t,t) of A and retrieve b, he can use an application that scans for b from now and checks if he meet A again (physically). 

Absolutely, which is why it is crucial that once revealed, SK_t are rotated and never re-used. Otherwise you have the possibility of performing long-term tracking as you mentioned.

**Comment by sc-fx** [comment]
Anyway, It is time to close the issue. Thanks for the following. Just propose that A not only contact the backend for declaring its infection, but also uploads random seeds when not infected.

**Comment by lbarman** [comment]
Sure, this been factored in :) Thanks a lot for the brainstorming !
