### ISSUE TITLE
Optional app recommendation to suspend BT activity if phone likely at rest

### ISSUE THREAD

**Issue by kugelfish42** [DP-3T/documents#116]
If non-location based sensors (accelerometer, magnetometer, charging status etc.) indicate that the phone is likely immobile for an extended period of time, the client could suspend its Bluetooth activity. Such a phone would likely be lying on a flat surface or a charging stand and proximity to its human owner is unknown at best.

Data collected from such a stationary phone would likely be unreliable and not transmitting any BT info would reduce the inevitable exposure to drive-by BT signal collection, mapping e.g. targeting residential areas during the night when many phones are lying on a desk charging.

**Comment by lbarman** [comment]
Hi @kugelfish42, thanks for the suggestion. It has been forwarded to the relevant teams.
As per the wardriving attack, our new version (Section 4 of the whitepaper) makes it harder, if you haven't read it.
If you have further input please feel free to comment.
Thanks!
