### ISSUE TITLE
Design 2 uses one EphID per day?

### ISSUE THREAD

**Issue by enriconardelli** [DP-3T/documents#119]
It's not so clear from description in page 12 whether in design 2 only one EphID per day is used or more. It seems just one, given that EphID_t is defined as a 128 bit long string, and BLE beacons' payload is 16 bytes, but given in version 1 more EphIDs per day are used a clarification would be useful.

**Comment by burdges** [comment]
I've seen 15 minutes written somewhere.  It should be 0.5 to 2 minutes so as to match the bluetooth broadcast rate.

**Comment by kennypaterson** [comment]
The whitepaper says, of option 1:

"We refer to the duration for which a device broadcasts the same EphID as epoch. The length of an epoch in minutes is a configurable system parameter which we denote as l."

For option 2 it says:

"As in the low-cost design, smartphones broadcast a frequently changing ephemeral identifier
EphID for a fixed duration l".

The whitepaper makes it clear, I believe, that many ephemeral IDs will be used in a single day period. To prevent tracking attacks based on correlating ephemeral IDs with MAC addresses, the ephemeral ID should ideally change at the same time as MAC addresses change.

**Comment by burdges** [comment]
It's important the ephids change exactly when the MACs change.  I think folks hope the Apple and Google effort makes this easier.  If you cannot know when the MACs change, then your only option is to rotate much faster, and sadly leak that the user is running the app.

**Comment by kennypaterson** [comment]
Sure, we know that, but thanks for the reminder.
