### ISSUE TITLE
Comic English level too advanced

### ISSUE THREAD

**Issue by jeffallen** [DP-3T/documents#124]
I showed the comic to my public health nurse wife who speaks English as a second language, and her feedback is that the English in the comic is not accessible.

In particular, she didn't understand "gibberish" and "shan't". And "folks" seemed too slang.

She also didn't understand the "what I said" list. She understood "said" as literally human speech, like what the user said, not what the phone broadcast. She proposes "what my phone said" instead.

**Comment by cascremers** [comment]
Thank you. We are welcoming translations to all languages. We already have French, German, and Spanish translations!

**Comment by rlavalle** [comment]
I believe OP was referring to the English level required to completely understand the cartoon.

**Comment by veale** [comment]
I agree strongly. We could definitely host a 'Simple English' version, if anyone wants to make one, like Wikipedia does. If you, or anyone else, makes one, please follow the instructions in the cartoon README to submit it. Thanks!

**Comment by marco-m** [comment]
hello @veale, I miss the relationship between agreeing strongly and closing this ticket :-)
The idea is not to create yet another language ("simple English"), it is to fix the existing English version...

**Comment by jeffallen** [comment]
This issue was for the original comic. In the reduced form, the English is not too advanced. Closing.
