### ISSUE TITLE
relation to Apple+Google Contact Tracing (today news)?

### ISSUE THREAD

**Issue by mvalla** [DP-3T/documents#125]
Hallo, 
what is the relation between DP-3T and today's announcement of Apple+Google to support Contact Tracing at the Bluetooth API and operating system level to enable development of apps from Government and Health Authorities?

https://www.apple.com/newsroom/2020/04/apple-and-google-partner-on-covid-19-contact-tracing-technology/

**Comment by zeno4ever** [comment]
From what I understand (please correct me if I am wrong) is that eg. for a iPhone you only can do certain things. Without support of the phone/api you would have to manual start the app and leave it open. If you switch to other app you can't scan other bluetooth devices. With support of google / apple you can develop an app that do the monitoring in the background, and the app would see all other devices even if the app isn't active. So in short this would be enable a much more reliable implementation of this protocol.

**Comment by Silmathoron** [comment]
I am not sufficiently well-versed in the details of Android and iOS to answer for sure, but I do not see why we actually need anything from G&A here:
* apps can be executed in the background (think of your email or text message apps)
* there are [alternatives for Push notifications](https://stackoverflow.com/a/20331937/5962321) such as [pushy](https://eladnava.com/pushy-a-new-alternative-to-google-cloud-messaging/) that do not rely on the GCM (for Android)

Am I missing something? Is it some specific Bluetooth issue?

**Comment by nohillside** [comment]
Looking at the published API (https://www.apple.com/covid19/contacttracing/) it seems that app developers don't need to bother with BT at all, they can just get the Daily Tracing Keys (in case the holder of the device has been tested positively) and request matching attempts between DTKs received from a server with the contact history stored on the device. This makes it very simple to develop such apps.

**Comment by mvalla** [comment]
Looking at the [proposed APIs](https://blog.google/documents/55/Android_Contact_Tracing_API.pdf), they are implementing together much more than just help on the iOS side or on keeping apps working in the background.

They implement the whole Contact Tracing protocol and features: cryptography and daily ID generation, scan, advertise, recordings on DB, contact calculation & match, offering high level methods like: startContactTracing(), onContact(),  getContactInformation(). 

So already on [Phase1 ](https://www.apple.com/newsroom/2020/04/apple-and-google-partner-on-covid-19-contact-tracing-technology/)(May) they will

> "release APIs that enable interoperability between Android and iOS devices using apps from public health authorities". 

Authorities would just need to use those APIs in their apps, and forget about Contact Tracing protocols.

Phase2 they will provide Contact Tracing protocol and functionalities directly at the operating system levels, so apps would not even need to use those APIs but just get the contacts alerts from the operating system.

**Comment by jwortelboer** [comment]
I programmed a Bluetooth app on iOS a few years ago. This is what I remember of the challenges at that time. Maybe it helps to explain the challenges on iOS a little. (vs Android?)

On Apple (iOS) there are strict rules to follow. You can bend the rules locally but when designing for release in the App store, the rules must be followed or the app will not be allowed in the store.

One of the common issues I hear is how to keep the app alive. Normally the app will go into suspend mode after a few seconds in the background. When the app is designed like a real evert driven app, it should not be a problem. But what if you want to do something in the background? To mimic background processing an app can ask for wakeup events on specific events. 
Most common event used fro this is the locations change event, waking up the app on movements. I think Dropbox still uses that to stay in the background longer. 
For Bluetooth the programmer can request BT specific events. You need to let the BT layer know what you are looking for and it will wake the app up on such data.
Continuously listening for specific BT data in the background and waking up on it is very easy.  
What I cannot comment on is how to keep acting like a beacon… never looked into that.  

There is an exception to background processing and that is a POST of GET of data over a HTTP connection. That can be done via a special event driven function and will keep on working in the background.It is for transferring bulk data. 

When requesting special events like locations changes and BT events, the app need to have such  a statement in its ‘entitlement’ file. That file will be checked when uploading to the app store and Apple will ask why you need it. The answer ‘for running in the background' is normally not the correct answer. 

The new API Apple announced might simplify things a lot.

**Comment by mvalla** [comment]
NO, they do not only solve these iOS background issues with BT, they implement the whole Contact Tracing protocol.

**Comment by kennypaterson** [comment]
@mvalla The DP-3T approach and possible approaches to contact tracing implied in the documents released by Apple+Google are broadly compatible. More information can be found here: https://github.com/DP-3T/documents/blob/master/README.md

**Comment by throwException** [comment]
Will DP-3T be built on the Applie/Google API restricted to governements?

**Comment by lbarman** [comment]
Hi @throwException, I just confirmed with the team: this is still being evaluated.

**Comment by pdehaye** [comment]
Why close the issue then? Is this still being evaluated?

**Comment by marado** [comment]
Indeed. One month later: is it still being evaluated?
