### ISSUE TITLE
Please clarify how this is decentralised

### ISSUE THREAD

**Issue by madduck** [DP-3T/documents#129]
How is the system you're proposing, which needs a backend for health authorities to reach out to potentially infected people, decentralised? The data are encrypted, the metadata are not.

**Comment by lbarman** [comment]
Hi madduck,
Thanks for your input. We think this question is answered in our FAQ, see [P7](https://github.com/DP-3T/documents/blob/master/FAQ.md#p7-why-do-you-call-your-design-decentralized-while-having-a-backend). Let us know if that doesn't answer your question!
