### ISSUE TITLE
solution to eavesdropping threat

### ISSUE THREAD

**Issue by mohitjaggi** [DP-3T/documents#137]
Apple/Google proposal has the same flaw as yours. See my [post](: https://www.linkedin.com/posts/mohitjaggi_contact-tracing-cryptography-specification-activity-6654848753578708992-5zhN) on linkedin. Also copied below:

The Apple/Google contact tracing approach is really cool! After a quick glance at its privacy design [ https://lnkd.in/gffFJfc ] I love it. There is a hole though: The diagnosis server can store the user's PII. This can be addressed by making the code of the server and client open source and letting us review it. Any intermediate routers can still guess based on traffic profile. That can be fixed by having every client (even those not infected) sending random bytes to the server in a way that observers cannot differentiate infection registering packets from the random ones.

**Comment by arelaxend** [comment]
Are we talking about the same thing ? 
https://www.linkedin.com/posts/alexandre-sarfati-01398a185_sur-le-protocol-pr%C3%A9liminaire-apple-android-activity-6654678451922046976-jK2n

https://github.com/DP-3T/documents/issues/144

**Comment by mohitjaggi** [comment]
haha...linkedin changed the link it seems. here
<https://www.linkedin.com/posts/mohitjaggi_contact-tracing-cryptography-specification-activity-6654848753578708992-5zhN>
it is

and here is the text in case the link is bad again:
Update: A similar design with the same flaw https://lnkd.in/gzyR6Uf The
Apple/Google contact tracing approach is really cool! After a quick glance
at its privacy design [ https://lnkd.in/gffFJfc ] I love it. There is a
hole though: The diagnosis server can store the user's PII. This can be
addressed by making the code of the server and client open source and
letting us review it. Any eavesdroppers can still guess based on traffic
profile (assuming communications are encrypted). *That can be fixed by
having every client (even those not infected) sending random bytes to the
server in a way that observers cannot differentiate infection registering
packets from the random ones.*
<https://covid19-static.cdn-apple.com/applications/covid19/current/static/contact-tracing/pdf/ContactTracing-CryptographySpecification.pdf>

**Comment by mohitjaggi** [comment]
Maybe. I don't understand the language in your post. Is it French?

**Comment by lbarman** [comment]
Hi all, thanks for the inputs! The issues are partially related ;)
@mohitjaggi: you mention two things: open-source (which I expect most solution will be, after all the designs are open-source and reference implementations are underway) and traffic-analysis+PII (also mentioned by @arelaxend).
For the latter, we are aware of it and will address it in a coming version of the whitepaper.

Would this answer the question ?
