### ISSUE TITLE
Separate protocol from algorithms

### ISSUE THREAD

**Issue by gardners** [DP-3T/documents#139]
I think we can short-circuit much of the algorithm specification part of things, so that we can get something out early, and still have the ability to improve it going forward:

1. Assume that each app instance uses some arbitrary mechanism to generate EthIDs and key material. We don't care what it is.
2. When a user's app decides it wants to upload something, it uploads the material together with a description of the protocol being used.  This should be a simple text-formatted sentence, e.g. something like: 

`DP3TA1:20200408:20200411:caf86e78a6cfe876ce798697acf87e96786acfe
`

Where DP3TA1 is the protocol identifier, in this example "DP-3T Algorithm 1",  the date fields indicate the validity/relevance time span of the data (after expiring it should be deleted), and the hex string following the last : is the protocol specific data.

This gets uploaded to the relevant backup server chosen by the app (which might or might not use a scheme like that described in #127).  

The apps may then download data for determining if they are at risk, according to the algorithms that they implement and expect the backend(s) to implement.  There should be a simple mechanism to determine which download protocols a given backend supports via simple HTTP query.

Together with appropriate update mechanisms for the apps, this allows the protocols to evolve rapidly in real-time, and for various nations to have different protocols, while still providing a means of interoperability.  

Implicit in this, is that the protocols themselves do not need to be finished to implement and begin distributing apps, which removes a key piece of latency in the whole system.

**Comment by kennypaterson** [comment]
Thanks. As you may have noticed, we are taking a different approach to the development of DP-3T. We are moving as fast as we can to having working apps and backend suitable for trials at scale. You will have seen the release of a significant amount of code today. Your point about being able to evolve underlying algorithms and protocol features is well-made and we will keep it in mind as DP-3T moves forward.
