### ISSUE TITLE
Public registry of infected ids, why not the ones at risk instead?

### ISSUE THREAD

**Issue by jasisz** [DP-3T/documents#14]
Why the registry consists of infected ids and not ones that were encountered by infected person?
This is what makes Location traceability much easier in decentralized scenario.

**Comment by lbarman** [comment]
Hi jasisz,
Thank you very much for your input. We think this is now addressed in the FAQ, see question [P1](https://github.com/DP-3T/documents/blob/master/FAQ.md#p1-why-dont-infected-users-upload-the-ephemeral-bluetooth-identifiers-ephids-they-have-observed-to-the-backend-server-so-that-other-apps-can-download-them-and-check-for-contacts-locally).

**Comment by jasisz** [comment]
@lbarman Sure, I'll close that one till it is in FAQ now.
