### ISSUE TITLE
Distance not always meaningful

### ISSUE THREAD

**Issue by frarude** [DP-3T/documents#140]
To measure the distance is not always meaningful for the risk of a person. 
What if, e.g. an infected person is sitting in the room next to me and we get never in contact?
So I will be forced to quarantine and have no reason. If I would have the information about the reason I could determine if there **is** a risk or not.

**Comment by arelaxend** [comment]
This is a relevant question. Still, the white paper does not reference any recommendations where "people" are forced to quarantine. In fact, autorities can not have access to the risks the protocol returns to people.

**Comment by kugelfish42** [comment]
Inferring relevant physical proximity from a a radio signal might be a bit questionable at best. Using device-pair callibration data might help a bit to filter out some irrelevant/weak contacts. E.g. some of the work from Bluetrace: https://github.com/opentrace-community/opentrace-calibration

**Comment by lbarman** [comment]
Hi all, thanks for your inputs!

It is a valid concern. Generally speaking, the technology for Bluetooth contact-tracing is under development; and it is hard to answer yet how well it will work in all use-cases. 
We note that it is fairly orthogonal to the overall design of the system (centralized vs decentralized), and some countries already open-sourced the Bluetooth contact-tracing "module"; we expect this to be a common part of most systems.

If you have any insight to share, feel free to reopen !
