### ISSUE TITLE
IP issue

### ISSUE THREAD

**Issue by alexandredeleze** [DP-3T/documents#15]
On page 9 of the data protection and security paper, you say that the backend server doesn't store information about IP address or time. But it means that users have to trust the implementation of the backend server and their administrator. We can mitigate this risk by using onion routing to transmit information to the backend server.
Another point is that you don't say how the secret seeds are secured on the smartphone. Do you consider encrypting it and how?

**Comment by kennypaterson** [comment]
Thanks for the comment. For onion routing, please see our FAQ, P5. Regarding seed encryption: our system has to run on different smartphone technologies, and access to secure, encrypted storage varies by platform and hardware. This makes performing meaningfully secure seed encryption more challenging (but not impossible). We don't currently plan to encrypt the seed, and our internal threat modelling suggests that doing so does not mitigate threats that we consider to be of high importance. We may revisit this as we harden the app in future releases.
