### ISSUE TITLE
Section 4 - Power Consumption implications of k-from-n EphID splitting

### ISSUE THREAD

**Issue by greigdp** [DP-3T/documents#150]
In Section 4, the text states

"We stress that this enhancement, even with the spread of the EphIDs​, is battery neutral. It requires no additional transmission or reception over the basic designs, and the additional computation is minimal."

This doesn't appear to be likely - it seems likely that phones could emit a beacon broadcast using "offload" to the BLE chip, thus allowing the CPU to enter a lower power state for more time.

If the beacon identity being emitted needs to change regularly in the same time interval, this would imply a need to wake the CPU up, stop broadcasting (if the beacon was immutable to the OS BLE library), select the new beacon payload, then resume broadcasting. This seems likely to use more power than simply broadcasting the same beacon for 10 minutes (which can be offloaded).

Is there a reference implementation yet that can be used to compare power consumption implications (as it's not clear exactly how much time a real device would end up holding the CPU awake in either case)?

**Comment by lbarman** [comment]
Hi @greigdp; thanks for the input! I agree, I also feel we oversimplified in this regard; I'll add a comment to fix it in the whitepaper.

As per the reference implementations, you have them [in the main repo](https://github.com/DP-3T), but there's no power consumption analysis done (yet?).
