### ISSUE TITLE
Absence of parameter to set the danger zone on a recommended 1,5 meters. 

### ISSUE THREAD

**Issue by LeysM** [DP-3T/documents#152]
Different versions of bleutooth have different ranges going up to 100 meters for Bleutooth4 and up to 400 meters for Bleutooth5.

In the document I couldn't find a parameter that would define the danger zone of the recommended 1,5 meters and thus restrict the distance between two bleutooth emitters where a warning would be triggered in case of "contact" with an infected person.

**Comment by noci2012** [comment]
Even plain BT 3.x could be used over 1.5Km with directional antennae in 2004/2005 see #73.

Then there is no "exact" distance between bluetooth devices as in meters... It very mcuh depends on the medium between the sender/receiver.  Radio Distance is different from mesured distance between 2 points. 
One can rely on the Maxwell equiations if needed, but those assume a void space.
All radio distances differ depending on energy levels used, how directional a signal is and materials a signal needs to pass. You can probably not "see" each others bluetooth device if there is a metal mesh between the equipment even if they are 10 cm. apart. A body of water will absorb quite some energy.

**Comment by mex2meou** [comment]
Hi @LeysM, thanks for the issue raised.

Please note that the aim of the application is to notify users about contacts made with infected people in the recent past and not to trigger a 'warning' when you are in the proximity of an infected person.

**Comment by LeysM** [comment]
> Hi @LeysM, thanks for the issue raised.
> 
> Please note that the aim of the application is to notify users about contacts made with infected people in the recent past and not to trigger a 'warning' when you are in the proximity of an infected person.

What I meant was : "Trigger a warning to the app" (= meaning registration of the contact in the app) not the user immediately. So that afterwards the user can get the notification about "contacts" you made with infected people. 

Today the contact should be registered when other persons or less then 1,5 meter distance. But tomorrow an other virus comes our way and it is 1 meter or 2 or 3 meters distance. Just make it future proof.

**Comment by LeysM** [comment]
> Even plain BT 3.x could be used over 1.5Km with directional antennae in 2004/2005 see #73.
> 
> Then there is no "exact" distance between bluetooth devices as in meters... It very mcuh depends on the medium between the sender/receiver. Radio Distance is different from mesured distance between 2 points.
> One can rely on the Maxwell equiations if needed, but those assume a void space.
> All radio distances differ depending on energy levels used, how directional a signal is and materials a signal needs to pass. You can probably not "see" each others bluetooth device if there is a metal mesh between the equipment even if they are 10 cm. apart. A body of water will absorb quite some energy.

Thank you @noci2012 for your feedback. You raised an interesting problem, that will need an interesting solution. Probably more difficult to implement then expected. 

But an app, that will register that you have been in proximity of infected people through a wall, is not very useful, not for the user, nor for the scientists that will need to analyse the data and make recommendation decisions based on faulty information. Specially in dense populated areas.
