### ISSUE TITLE
Secret sharing and parameters

### ISSUE THREAD

**Issue by vaudenay** [DP-3T/documents#154]
There are several parameters of importance:
- the epoch duration (say t)
- the beacon frequency f
- k and n
(We could say that k=1 is the version without secret sharing.)

Does the app have any control on f? Or is it imposed by the hardware?
What could be the relevant parameters t, k, n?

EphID is split into n shares t*f/n times.
The receiver must catch k out of n shares of the same split to recover EphID.
Security requires k/n high so that distant receivers are unlikely to catch EphID.
Functionality requires to be able to record long encounters but encounters lasting less than a fraction k/n in each slot of n/f time during an epoch cannot be recorded.

It is probably not a good idea to set n too large as suggested in the paper.

Example: t=15min, f=1Hz, n=60, k=60 (high k/n for security).
A customer meeting a vendor during 5min with the vendor disappearing in the back shop at least one second in every minute will catch no EphID and the encounter will not be recorded.

Example: t=15min, f=1Hz, n=60, k=30 (lower k/n for functionality).
A customer meeting a vendor during 5min with the vendor staying less than 30sec every minute with the customer and disappearing in the back shop the rest of the time will catch no EphID and the encounter will not be recorded.
In the same time, a distant receiver catching 50% of beacons during a minute catches EphID.

Example: t=15min, f=1Hz, n=10, k=10 (lower n with high k/n).
A customer meeting a vendor during a full slot of 10sec will catch EphID.
A distant receiver must catch all beacons during 10sec too.

**Comment by kennypaterson** [comment]
Thanks, this is helpful input that will inform our thinking as we do a more detailed design of the secret sharing concept.
