### ISSUE TITLE
Secret Sharing in Practice

### ISSUE THREAD

**Issue by a8x9** [DP-3T/documents#156]
When you are in contact with multiple persons, how do you know which share was emitted by which phone? Basically, how do you correctly regroup shares?

- On iOS, you don't have access to the BLE advertisement packets MAC address.

- On Android you could use the MAC address, assuming the MAC address randomization is synchronized with your EphID change frequency. But I don't know if you can control that, [this article](https://www.bluetooth.com/blog/bluetooth-technology-protecting-your-privacy/) suggests that the randomization timer is implemented in the Bluetooth chip firmware.

Did you take these limitations into consideration for this new design? If yes, how do you solve the above problem?

**Comment by galadran** [comment]
Hi a8x9, 

You are right that for Secret Sharing, we would need to either transmit an additional small identifier or have access the to MAC address of incoming packets. Given Google and Apple's existing engagement with the contact tracing community, we are hopeful they might adopt our proposal and support it as part of their API.

**Comment by vaudenay** [comment]
Depending on the choice of the secret sharing (e.g. Shamir secret sharing), you may have to transmit the index of the share as well.

**Comment by galadran** [comment]
That is true, although using time synchronisation to index incoming packets may also work.

**Comment by lbarman** [comment]
Closing as this seem addressed...
