### ISSUE TITLE
Some thoughts on possible use cases and user groups

### ISSUE THREAD

**Issue by Selinde** [DP-3T/documents#16]
What is the effect of not knowing the identity of the people that are infected or that are at risk? I understand completely why identity of app users is not known in the design, and I agree with it. However, we need to know the possible negative consequences of that as well in order to mitigate them. I am thinking about people not taking the warning that they are at risk serious, for example. Or, on the other hand, people becoming very scared when they hear that they are at risk. What about people that have cognitive issues leaving them unable to understand the warning? What are ways to get help to those people if we are not sure who they are?

A related issue is that we do not know who does not have the app. You mention that some extremely cautious people might not install the app. However, this is not the only group I would expect not the install the app, and I would expect the people not installing the app not to be distributed evenly throughout the population. For example, a lot of the elderly do not know how to install and use apps. Some might not regularly use a mobile phone. It is to be expected that in general people tend to interact more with people similar to them. This means that 'pockets' could exist of people not using the app where the infection can go around easily. Especially when it concerns the elderly, this might have serious consequences. To what extent will these things be a problem in practice? Would it be somehow possible to detect the 'edges' of these groups not using the app to make intervention in the groups possible when they get infected (and should we do this)?

Another question is whether people who have the app will have a false sense of safety and therefore will be taking risks. Would this be a problem and could be do something about that?

In addition, people could also claim that they have been warned because they want to get tested and tests are scarce, for example. Would it be possible to check whether someone has truly been at risk, or is it easy to fake this?

It also could be interesting to base the risk score not only on one contact, but on multiple contacts with the same or different infected persons. Also, for someone who has been in contact with more people or is in regular contact with many others (e.g., someone working at a supermarket), it might be useful to get tested with lower risk scores than people who hardly have any contact with others. Especially if tests are scarce. However, a medical specialist should probably decide whether this is useful.

**Comment by jasisz** [comment]
1. The assumption is that the person at risk should initiate the contact. It could be made very easy within app, but it shouldn't be possible to initiate the contact the other way - this is the main privacy consideration of this project.
2. (and 3) The main thing is that people should be able to use in-app status to e.g. go to work, go to some small parties, etc. It should be beneficial to a person installing an app to have it, not risking any privacy and so on.
3. This is possible, as they can cryptographically confirm that a risky id was theirs.

**Comment by Selinde** [comment]
I understand that the person at risk should initiate the contact and I agree that this is an important privacy consideration. I am not suggesting to change this. However, it is important to determine what the possible effects of this are such that they can be mitigated. This might be done by changing or adding to the design, or in other ways. For example, can users only view the warning only for a short time, or is it possible to store the warning for a longer time such that a caregiver can check the phone regularly? What are the possibilities to provide information targeted at certain vulnerable groups about what they should do? And so on. I think it is important to consider these things as well.

**Comment by vanvictorlim** [comment]
This issue needs to be broken down into specific detail and discussion per question. The flow of thoughts are too much to answer in one reply.

**Comment by Selinde** [comment]
No problem, shall I just break it up and add several new questions?

**Comment by s-chtl** [comment]
Hi All, thank you for your inputs. We are actively discussing with epidemiologists to solve those issues. We'll update the documentation when we have new information.
Closing the issue for now.

**Comment by Selinde** [comment]
Good to hear you are discussing it. Please let me know if I can be of any other help.
