### ISSUE TITLE
Risk Model: App provider misssing?

### ISSUE THREAD

**Issue by adewes** [DP-3T/documents#161]
Protecting individuals from government surveillance seems to be one of the main selling points of this framework. In that regard I don't understand how this protocol protects against an adversary that has control over the application on the phone (which will often be the government). It seems there's no mention of this in the risk model and no corresponding adversary in the threat model for this?

I think a likely scenario might be that a government first issues a trustworthy version of a contact tracing app based on this proposal that respects user privacy. Later when the app is widely used it might decide that it wants to reconstruct the full social interaction graph. To do so, it can provide an updated, malicious app which simply does the following things (assuming that FKs/EphIDs are specifically protected by the OS e.g. via the Google/Apple framework):

- Upload the FK values of all users to the backend (i.e. simulate an infection event for each user)
- Download all FK values obtained like this to each phone (possibly in chunks or using a heuristic that reduces the search space, e.g. using geographical information about a given user) and query the local store for these FK values via the OS API. This will reveal all contacts that the particular user had.

This assumes that the government can also issue valid certificates for registering an individual as infected, which is not unlikely as the government usually has control over the public health system. This attack would be relatively easy to perform and would allow the full reconstruction of the interaction graph if I'm not mistaken? Even with countermeasures such as only supporting batch-wise/k-anonymous checking of FKs (as seems to be the case in the Apple/Google SDKs) it would still be possible to do this (albeit with greater difficulty) by e.g. inserting fake FKs to fulfill the k-anonymous querying criteria (as in my understanding the app does not have a means to distinguish a valid from a fake FK), or querying with different subsets of FKs to combinatorically de-anonymize the results.

It should be possible to defend against such extraction measures by e.g. implementing rate-limiting and additional security measures on the OS level, but even then it seems quite hard to defend against an adversary that has control of the app.

I think it would be reasonable to add a corresponding threat actor to your threat model for this, and clarify how you plan to defend against it, as resilience against government surveillance is one of the main selling points of the protocol.

If my analysis is based on a wrong understanding of the protocol or I overlooked something that would make this scheme infeasible please let me know, happy to receive some feedback on this and looking forward to discuss!

**Comment by adewes** [comment]
Did you remove some of the discussion of this issue @lbarman?

**Comment by noci2012** [comment]
Or add functions to the app that can be activated upon request to divulge more data than intended when the phone is examined or queried by a "special" app/message/...

**Comment by lbarman** [comment]
> Did you remove some of the discussion of this issue @lbarman (just wondering because I thought there were comments, maybe I'm wrong)?

I absolutely did not. :)
