### ISSUE TITLE
Reduce false positive contact by taking Bluetooth power RSSI into account

### ISSUE THREAD

**Issue by ChrisDaumer** [DP-3T/documents#167]
The idea is to take into account bluetooth RSSI in the scoring formula. 

RSSI is impacted by obstacles such walls. For exemple, if RSSI is considered, the system can prevent to warn people who were not in the same appartment/room.

The scoring formula could be :
`score = f(inter_connexion_duration, average_rssi_during_inter_connexion)`

**Comment by lbarman** [comment]
Hi @ChrisDaumer, thank you for your input! Unless I'm mistaken this is the case already; the phone compares the received EphIDs (or seed/bloom filters) with its local contacts, which contains duration/RSSI/etc.
Does this answer your question ?
