### ISSUE TITLE
Possible re-identification risk due to misaligned EphID and MAC rotation

### ISSUE THREAD

**Issue by adewes** [DP-3T/documents#168]
Both Android and Apple devices use MAC rotation mechanisms to counteract fingerprinting based on the Bluetooth LTE MAC address sent in advertisement packets (see e.g. https://arxiv.org/pdf/1904.10600.pdf). If this mechanism isn't exactly synchronized with the `EphID` rotation sequence it would allow an adversary to associate consecutive `EphID`s with the same device if he/she manages to capture two advertisements from a device where either the `EphID` was rotated but not the MAC address, or vice versa. As it seems that apps do not have control over this mechanism it will requires OS level support to guarantee perfect alignment, and it seems this would tie the `EphID` roation schedule to a multiple of the MAC rotation schedule.

**Comment by lbarman** [comment]
Hi @adewes, thanks for your input!
We are aware of the issue, and it is already discussed here: https://github.com/DP-3T/documents/issues/69. Could we move the discussion there and close this issue ?
Thanks

**Comment by adewes** [comment]
Sure, I used the search function to see if there was a similar issue but didn't find #69, closing this.
