### ISSUE TITLE
Allow tracing at locations where people store devices in locker rooms

### ISSUE THREAD

**Issue by cmbntr** [DP-3T/documents#173]
Use case:
People visit a sports club. There are different locker rooms (women, men). Some people take their devices to the workout, some leave them stored at the locker room. The locker rooms might be big, so there is no guarantee the stored devices record each other. On the other hand, two devices might be stored next to each other and record a contact, but their users might not have contact during their workouts.

**Comment by cmbntr** [comment]
One possible solution could be that users activate an 'away from device' mode #174 when arriving at the location (to prevent false positives) and upon checkout all users link their visit to a designated device which represents (and always stays at) the shop #175.

This would trace the users which visited the location at the same time by being linked in a 'star topology' to the designated device.

Maybe the tokens produced by the designated 'shop device' must somehow reflect that the contacts traced by them are of a different kind than 'regular' contacts.

**Comment by cmbntr** [comment]
Another possible solution could be that the location emits special beacons in the locker rooms and the workout area. This beacons are seen by every device during the stay at the location.

When the user leaves the location (and thus looses the contact to the beacons) the app asks the user if the visit should be traced as a 'shop visit' and other device contacts (e.g. false traces from near devices in the locker room) should be discarded for the time period of the visit.

**Comment by lbarman** [comment]
Hi @cmbntr, as you point out the (Bluetooth) contact tracing will have many corner cases :) your options are valid, potentially combined with some detection of if the phone is moving or not (there is code for this already). Forwarding to the dev team.

> Another possible solution could be that the location emits special beacons in the locker rooms and the workout area. This beacons are seen by every device during the stay at the location.

cool idea but which requires a bit of infrastructure effort, definitely a future improvement.
Thanks!
