### ISSUE TITLE
Allow users to specify 'away from device' periods

### ISSUE THREAD

**Issue by cmbntr** [DP-3T/documents#174]
Allow a user to record time periods spent away from the device.
Maybe this should be limited to periods within the last 24 hours.

Use Case:
User visits a sports club and stores his device in the locker room and then walks away for a 90 minutes workout. Another user enters 20 minutes later, storing his device next to the first users device. The two users will not have contact within the sports club.

**Comment by kugelfish42** [comment]
For devices which have a motion sensor (accelerometer) it might be more effective for the device to suspend its activity while it is absolutely still and quite likely separated from its human. This would also help to extend battery life.

**Comment by lbarman** [comment]
Hi both, thanks, added to a list of possible extensions for the app!
(ps. If I'm not wrong it's already planned that you can turn on/off the tracing, but still)
