### ISSUE TITLE
Connection between DP-3T and the governement-only-API by Apple and Google?

### ISSUE THREAD

**Issue by throwException** [DP-3T/documents#178]
Does DP-3T target any Apple/Google API reserved for governement-sanctioned apps as mentioned in the article below?

https://www.heise.de/newsticker/meldung/Coronavirus-Kontaktverfolgung-wird-Teil-von-Android-und-iOS-4702166.html

In my opinion, this would be very bad, as it would keep people from building the app themselves, thereby taking control from the them.

**Comment by lbarman** [comment]
Hi @throwException, let's continue the discussion on the existing thread: https://github.com/DP-3T/documents/issues/128. Thanks!

**Comment by throwException** [comment]
Actually neither  #125, #128, nor the Readme or FAQ answer my question, unless DP-3T is entirely superseded by the Apple/Google API.

**Comment by lbarman** [comment]
Answered you on https://github.com/DP-3T/documents/issues/125
> this is still being evaluated.
(sorry that I cannot be more helpful at this stage!)
Closing.

**Comment by throwException** [comment]
It seems the question was answered, albeit not here:
https://www.swissinfo.ch/eng/digital-solution_contact-tracing-app-could-be-launched-in-switzerland-within-weeks/45706296

**Comment by lbarman** [comment]
Yes, quote for reference:
> “[The swiss system] will be based on the DP-3T concept of EPFL and will leverage the new Google and Apple Contact Tracing APIs as soon as they are available,” Pascal Strupler, Director-General of the Swiss Federal Office of Public Health, is quoted as saying in a press release.

Note that [the Swiss system] is not exactly DP3T. DP3T is the overall design and the Swiss system will likely implement DP3T making local decisions too. Notably, public reference implementations of both will likely be separate.
