### ISSUE TITLE
Secret Sharing: probabilistic effects on Epoch changeover

### ISSUE THREAD

**Issue by cluck** [DP-3T/documents#181]
The current proposal of spreading the EphID over multiple beacons by means of secret sharing may pose receivers collecting shares over a change of Epoch at a disadvantage.

It might be worth exploring the possibility to re-use some of the shares during an overlapping time slot to account for concurrent new and pending listeners. This way both listeners will be able to complete 'their" EphIDs by the means of the same share, without gaining any knowledge about the "other" EphID.

(Also related: #154)

**Comment by cluck** [comment]
Correcting myself, I've wrongly assumed that Shamir's secrets fₙ(xₙ) = EphID + a₁x + a₂x² + ... + aₙxⁿ  can be in part freely choosen, but that isn't the case. Polynomial coefficients a₁ ... aₙ are, but they are to remain secret.

That is, sharing shares is likely not a viable solution.

**Comment by lbarman** [comment]
Hi @cluck, thanks for your input and sorry not to be more responsive. 

> But much more importantly, re-using information across EphIDs enables a long-time observer to understand that two EphIDs are from a single source, which defeats the whole purpose of using EphIDs.

Yup, this sound like something we need to avoid, especially since in-epoch tracking is already a concern. Would you see a fix ?

Thanks
