### ISSUE TITLE
Write in doc that DP-3T app works fine without SIM card nor GPS sensor

### ISSUE THREAD

**Issue by pelinquin** [DP-3T/documents#184]
There is still a lot of confusing for non-computer-scientists (at least in France) that contact tracing well designed app, like the DP-3T,  needs a phone number (a SIM card) and/or a GPS sensor.

Furthermore, I do believe that a lot of new 'app' will follow the BLE contact principle to provide very interesting services like voting, payment, traveling, certification, including a dedicated crypto stack....just think of the problem of proving that you are a human being, not a bot.

So, I think it is important to say that the "mobile personal computer" does not need the phone fonction...A wifi or wired connection once a day is enough to communicate with backend.
A basic ESP32 board or equivalent will also work....please write it in the White Paper.

People may realize that they don't need a 3G-4G-5G PhoneCall Suscription.
That also means that DP3T can work on basic iPad

#56 OK for using recent hardware. The point here is communication on SIM card / GPS  for DP3T

**Comment by cascremers** [comment]
Indeed, this is correct. We do not require SIM card nor GPS.

We'll try to integrate this in the next versions.

**Comment by pelinquin** [comment]
Merci !
