### ISSUE TITLE
Worldwide app: no option needed to send data to local epidemiology research center

### ISSUE THREAD

**Issue by pelinquin** [DP-3T/documents#187]
Anyone can contact (phone call) any time her regional health authority to describe any symptoms or any risk-value given by her DP-3T app. Each country has a specific number.
**The risk-vector-value (multi-dimensional) should be universal, defined worldwide** for a given virus, and should help to sort people calls according to the government strategy.
The health authority may ask the caller to go to the hospital, to wear a mask, to go to quarantine, to apply for a test, or to wait, and may ask many informations (name, location, age, history moves,...) All those data can be shared with epidemiologist. But it's up the the citizen to give the right data to health autority.

**So, there is absolutely no need to send, even voluntarily, app raw data to epidemiologists.**

The purpose of the app is not to help epidemiologists, it's to be "one step ahead" by decentralized citizen behavior acting to protect herself.

Any data requested by epidemiologists can be found with health authority.

By the way, it isn't explained in the doc why epidemiologists would require DT-3T data.
Removing this feature would help to make the app worldwide adopted and would simplifies HMI/translation.
Keep it stupidly Simple !

**Comment by s-chtl** [comment]
Hi @pelinquin, thanks for your input. We are actively discussing with epidemiologists to figure out their exact needs and update our documentation. 
Thanks for raising the concern we will keep it in mind.
