### ISSUE TITLE
Charts and diagrams for press use

### ISSUE THREAD

**Issue by gardners** [DP-3T/documents#190]
If you want your valuable work to get noticed and picked up by the press, you need to have easily findable and usable charts and diagrams that show the difference between your system and the default centralised approach, and the various horrible things that can happen with a  centralised approach.  

In short, you want to make reporter's work as easy as possible to report on your work as a better alternative.

**Comment by gardners** [comment]
Any further thought/movement on this? I am talking to reporters here in Australia, and would really like to be able to share diagrams, animations or infographics with them that show the difference between the Right Way and the Orwellian Way of contact tracing.

**Comment by lbarman** [comment]
You're absolutely right, bumping this issue internally...

**Comment by lbarman** [comment]
There you go, see the `graphics/` folder. We know this is not close to a press kit, that's what we have right now, sorry ! Please let us know if you'd like other documents !

Note: The DP3T logo is *temporary* and likely *not* the official one (which will come) and should not be used in the press / in official apps / etc.
