### ISSUE TITLE
Using GPS to download only infected from regions you've travelled to

### ISSUE THREAD

**Issue by antonio54321** [DP-3T/documents#192]
Creo que es inviable que el teléfono cargue todos los contagiados de Europa.... pero únicamente tendría que cargar los contagiados de los Códigos Postales por donde vaya viajando, no todos, esto seria totalmente viable.

I think it is unfeasible for the phone to load all the infected people in Europe ... but it would only have to load the infected ones from the Postal Codes wherever it is traveling, not all, this would be totally viable.

**Comment by lbarman** [comment]
Hi @antonio54321, thanks for your input! This falls in the roaming/intercompatibility topic, which we are working on and we know is a "hard" topic. If you have specific inputs, please let us know!
Thanks

**Comment by antonio54321** [comment]
Lo siento Ibarman, me es muy complicado, escribir en ingles, mi idea seria que el móvil le diera al sistema las coordenadas exacta del GPS pero que el sistema le devolviera solo los contagiados en su código postal (aproximadamente 30.000  personas a su alrededor). esto reduciría el ancho de banda necesario, así como el almacenamiento.  Cuando el sistema GPS interno detecte que se ha movido mas de 5 km. por ejemplo vuelve a "refrescar" los datos. (un radio determinado a su alrededor)

**Comment by lbarman** [comment]
No problem, the goal of this platform is to discuss :)
