### ISSUE TITLE
Avoid sharing of IP address 

### ISSUE THREAD

**Issue by ryanbnl** [DP-3T/documents#195]
First: great work, the design as described in the white paper is one of the best I've seen so far.

However, there is one problem: when a patient reports themselves as being infected they will share their IP address with whoever is hosting the server side. This will allow them to be identified pretty easily, especially by state actors or parties such as Google, Facebook and Apple.

This can be avoided by having the Doctor make the report, not the User.  Let the User generate a token which can be scanned by the Doctor authorizing the Doctor to report the User as infected.

**Comment by lbarman** [comment]
Hi @ryanbnl, thanks for your input ! 
May I redirect you to the pinned thread: https://github.com/DP-3T/documents/issues/193
in short, the current mitigation is through dummy uploads.

> This can be avoided by having the Doctor make the report, not the User. Let the User generate a token which can be scanned by the Doctor authorizing the Doctor to report the User as infected.

yes, this is one of the possibilities :)
Thanks!

**Comment by ryanbnl** [comment]
Fantastic, thanks for your reaction @lbarman. This really is the gold standard project.
