### ISSUE TITLE
Second visit to hospital problem

### ISSUE THREAD

**Issue by a8x9** [DP-3T/documents#2]
Thanks a lot for releasing these documents.
I'm looking forward to the upload of the reference applications source code.

I have one remark regarding section 3, *Handling infected patients*, of the *Data protection and Security* document.
If I understood correctly, the following steps would happen:

1. Hospital calls patient to inform them of positive test.
2. Patient goes back to hospital with their phone.
3. Hospital generates an authorization code.
4. Hospital uploads this authorization code to backend.
5. Patient scans authorization QR code.
6. Patient sends (SK<sub>t</sub>, authorization code) to backend.

This assumes that the patient will go to the hospital a second time after being tested positive.
In practice, this is rarelly the case. Patients receive the results by phone and should stay isolated and not go back to hospital unless necessary.

What I propose would be to simply change a bit the order of these steps:

1. Hospital generates an authorization code and attach it to the patient test.
2. Patient scans authorization QR code and keep it locally.
3. When test results arrive and only if positive:
4. Hospital uploads authorization code to backend.
5. Hospital calls patient to inform them of positive test.
6. Patient sends (SK<sub>t</sub>, authorization code) to backend.

It would also be nice to have more information about the backend.
For instance, how does it identify / authenticate who can upload new authorization codes?
Do you plan to also release the source code for the backend?

Thanks and cheers!

**Comment by timoll** [comment]
The QR code could also be a private key. That way the test result itself could be send via the app. 

It would make it easier for laboratories to give the test result faster and time is of essence when it comes to contact tracing.

I assume that this would be for a latter version as it is not a essential feature right now.

**Comment by kennypaterson** [comment]
Thanks for this thoughtful contribution. Our thinking on how to handle this part of the process is still at an embryonic stage, but clearly requiring a person to visit a hospital twice to complete the process would not be ideal. Your input here will be valuable as we produce a detailed design of this component.
