### ISSUE TITLE
Targeted hacking can detect 2 persons met each other

### ISSUE THREAD

**Issue by gscokart** [DP-3T/documents#20]
If a hacker target 2 mobiles, and find the same ephid (of a 3rd persons) in the same period, he could deduce that the 2 persons probably met each other (with a third person).

This could be partially mitigated if, instead of publishing one ephid at a time, the device would publish n IDs, and the receiver only keep one of them randomly selected.

(Not sure if it is possible with BLE)

**Comment by snakehand** [comment]
There is no reason why the app should reveal the recorded ephids outside its sandbox. It only needs to reveal a match score based on published infected SKs. I believe app data (at least on Android) is protected agains being read by other apps, so the only threat would be a phone that is hacked with root privileges. But if you are running around with the devils phone, should should not expect any privacy at all.

**Comment by mex2meou** [comment]
Hi there, thanks @gscokart for the issue raised!

Indeed, as mentioned in @snakehand's response, targeted hacking could reveal much more juicy information that goes beyond contact tracing.
