### ISSUE TITLE
Asynchronicity as a relevant privacy mechanism?

### ISSUE THREAD

**Issue by adewes** [DP-3T/documents#203]
Apologies for spamming the issue tracker, this is an additional concept that I thought about and which I haven't seen discussed here yet (though maybe you discussed this internally already). I think it's possibly a bit far-fetched and might not be practical but could still lead to intersting insights.

In my understanding, one of the central problems of proximity tracking is that is happens synchronously: I can observe `EphIDs` and record additional information about the specific circumstances under which I saw them. That can in turn allow me to relate the `EphIDs` to specific persons. As the `EphIDs` might later be associated with health information this poses a serious privacy risk to these persons.

If we could find a way to make the tracking happen asynchronously, an observer would no longer be able to correlate `EphIDs` with the specific circumstances under which they were observed (or at least have more difficulty doing this), which would decrease the privacy risk of the related persons.

I thought about several ways to achieve this asynchronicity, here's one idea:

Instead of directly exchanging `EphIDs`, users would broadcast "exchange tokens" that would be recorded by other users. These tokens could then be exchanged for the real `EphID` tokens at a later point in time. The exchange should happen in a way that hides the exact correspondence between a specific token and its `EphID` value, creating asynchronicity between the `EphID` and the observation circumstances. Building such a protocol in practice seems to be difficult though. I considered e.g. the following approach:

Use a centralized backend to which a user can upload exchange tokens together with his/her corresponding `EphID`. Other users can then (anonymously) query the system for the exchange tokens they have observed and download the corresponding `EphIDs`. A suitable anonymity mechanism (i.e. a naive idea would be requiring users to query at least k exchange tokens at once) could ensure that a user cannot associate specific exchange tokens with specific `EphIDs` and only receives results based on a larger group of exchange tokens.

The problem with this is that a user can easily circumvent the anonymity mechanism if the generation of tokens is unrestricted and if he/she can pose arbitrary queries to the exchange server. Doing this e.g. with forged tokens or tokens generated from devices with known `EphID`s would for example allow an adversary to easily break a k-anonymity mechanism as outlined above. I think there might be ways to counteract this but I wasn't able to come up with a good solution yet, maybe someone with more expertise in cryptography would be able to do this though (I am e.g. not sure if mechanisms like oblivious state transfer could be used to create a secure exchange mechanism).

I think this might be worth investigating a bit more though as solving the synchronicity problem would also solve most of the remaining privacy and anonymity problems posed by the system. I'm happy to hear your feedback and ideas on this therefore!

**Comment by adewes** [comment]
Closing this as I don't think it's doable.

**Comment by hofra** [comment]
Your approach can work with a change:
instead of:

> Other users can then (anonymously) query the system for the exchange tokens they have observed and download the corresponding EphIDs

We have:

> Other users can then (anonymously) send the tokens they have observed (again) to the system and the server will return if these tokens match an infected person's own stored tokens (that got uploaded to the DB once they have been tested positive)
 This means the User stores both their own issued token and the observed ones for the last 14 days.

Can this work?
