### ISSUE TITLE
Coronavirus COVID-19 - Calibration Method and Proximity Accuracy

### ISSUE THREAD

**Issue by MecJames** [DP-3T/documents#204]
Attached you will find a publication. It describes the complete solution of the Calibration Method.

(https://www.researchgate.net/publication/340647120_Contact_Tracing_Coronavirus_COVID-19_-Calibration_Method_and_Proximity_Accuracy)

Considering the communication between the Bluetooth Transmitter and Receiver, there are three areas, Transmitter, Radio Channel (Fading and Directivities of Smart Phones), and Receiver. In the attached Doc you can find the solution of the TR and RX problems, e.g. how to remove all the deviations between different Smart Phone Types. The remaining challenge is the Radio Channel.
If the systematic errors are not removed by the calibration method, then BLE will be completely unsuitable for the intended purpose of interrupting the infection chains.

In (https://github.com/opentrace-community/opentrace-calibration) only the TX has been considered.

**Comment by lbarman** [comment]
Awesome, thanks @MecJames! Forwarded to the correct team.

**Comment by MecJames** [comment]
Dear Ludovic,

you have just closed the issue #204. Who is responsible for this point? This point is much more than just an issue.

 

From the abstract of my paper I just wanted to provide to you:

“If the systematic errors are not removed by the calibration method, then BLE will be completely unsuitable for the intended purpose of interrupting the infection chains.”

 

Please give me a the right contact.

 

Best regards

**Comment by fneeser** [comment]
Hi @MecJames
FYI, I recommended to adopt the calibration and correction method described in your paper -- see my analysis in https://github.com/DP-3T/documents/issues/188#issuecomment-618666631 of how the method could be implemented, also considering the iOS - Android interoperability.

**Comment by MecJames** [comment]
Hi Fredy,
I fully agree, there is a need to do the corrections. I am working on a test specification which describes how to qualify reference phones. The second part describes how to measure the correction factors for the different smart phone types. This will be published by the GSM Association. Everybody can participate to deliver correction factors. The aim is that for almost all smart phone types correction factors will become available.

There is a need that one correction factor must be transmitted with advertising of BLE.

From my point of view, the specification of Apple and Google is not considering these effects.

Best regards,
Hans-Juergen

**Comment by fneeser** [comment]
Hi Hans-Juergen,
I just noted that version 1.2 of Apple and Google's new "Exposure Notification - Bluetooth Specification" (see https://www.apple.com/covid19/contacttracing/) now has 4 additional bytes of metadata in the Advertising Payload.
Byte 1 of the metadata is specified as "Transmit power level".
Bytes 2 and 3 are reserved "for future use" and might be used to convey a "Transmit power adjustment".
Not sure if Apple and Google are aware of your paper - have you been able to establish a contact with their Bluetooth teams?

Best regards,
Fredy
