### ISSUE TITLE
pursue a more powerful approach against centralized competitors

### ISSUE THREAD

**Issue by diedicar** [DP-3T/documents#205]
It seems that DP3T has been cornered. Maybe was not powerful enough to compete with centralized alternatives, maybe I`m wrong but I think that with an extension it could have better odds:

1let`s create a system in which every node can voluntarily spread information exactly as happens now for infected nodes that are certified by swabbing, presently swabbing is the only proof in the system

2at the same time every node should be non linkable to the previously certified infected

3hence the authorities will not know the shape of the social graph, but instead will know the aggregate number of nodes that have a certain distance to the infection sources, giving an idea of the overall intensity of social contacts and the contagion potential in every instant.

4 users will have an idea of their connectedness to contagion sources and could be suggested to self insulate, given a work leave and other accessory policies. Such suggestions can vary depending on the aggregate risk and can be calculated locally

In order to do so something like a "virtual swabbing" a proof that authorizes publishing of information is needed, in issue #85 is presented a scheme that could fit the goal. In issue #86 It is presented as just one step, but it seems me that the same logic can be iterated to publish  nodes at an arbitrary distance from the infected. Some details are missing and  probably much more elegant solution for virtual proofs can be foundin this generalized thread.

**Comment by cascremers** [comment]
Thanks for this. For now we are pursuing the DP3T approach, but we definitely encourage the development of alternative solutions, and compare on technical merits once complete.

**Comment by diedicar** [comment]
Thank you for the kind reply, It is the very same approach of DP3T, just made scalable and provable. It leverages the proof scheme proposed in issue #85
