### ISSUE TITLE
user story

### ISSUE THREAD

**Issue by pitsch** [DP-3T/documents#207]
userstory

karla has a smartphone
she installed a corona tracing app
karla is german
she feels sick
she has a temperature 
she coughs, has no taste and has a headache
she calls her doctor
the doctor says she should get a test
and quarantine herself
and calls the health office for her
karla gets a link to download a registry and instruction kit to her phone
she gets a personal https page from the health office with dashboard and links
she agrees to use this page only from these two devices
     she finds a neighborhood care service
     the friendly volunteer care giver goes to the shop for groceries
     she finds an online government service to make sure payments come in
     she joins a video chat board where people meet who were infected already
     she gets a free test account for a streaming provider
     she doesnt feel so bad any more
one day later she gets a test kit
she uses it, sends the test kit back, which is picked up by a messenger, it has a qr code on it
she scans the qr code with her phone which links to the health office
she clicks through user agreements and fills out missing information
she gets a confirmation email and unique pin to keep secret
she gets an tracking number with link and estimation how long it will take
     she goes to her chat board and shares her experience
     she follows a bunch of curated links show how to keep hygiene, mentally as well
     the page is also giving her information of the probablity of getting severly ill based on the   numbers in her district, her age, adress etc.
     she gets called once a day by a friendly volunteers who ask if she is ok 
     there is a quarantine diary she can use to keep a daily routine 
     her doctor gets access to her diary and calls her if the temperature is too high
     she starts to use an open source streaming tool and posts a little vlog
     other people see it and give her good feedback
after 3 days the test arrives
it is positve
she goes to her health office page to look for further info
     she watches a video where she is adressed personally of what to take care now, chats with the   health office and gets a personal consultation.
she agrees to trigger the contact tracing run 
she enters her pin into her tracing app and gets an extra pin for 2 pass auth
she gets a list of contacts including their location
it shows that some of her facebook friends and twitter followers were part of it
she gets a unique link she can use to inform her friends they got infected without tracing back to her
     one of them is her boyfriend hans
     she sends him a chat voice message and attaches a link to get a quick covid test.
the phone uploads the contact traces
    she agrees to trigger automatic warnings and selects a few nice personal emoticons. 
hans has a smartphone
he starts to feel sick
he downloads the corona tracing app
to activate he watches a short video about the infection law, reads through a bullet point list and clicks agree.

**Comment by pitsch** [comment]
since you do not have one user story yet this was a first trial.

in germany every positive test starts with a lawful registration of the private data set at a local health office. from there the test gets validated and usual contact tracing happens organized via telephone. from this point on you can start a chain of trust. we have about 260 of such health offices in germany, and each of them has been recently upgraded with more equipment and larger teams. i

i could not find any hint in your documentation about interaction acknowledging the legalities and administrative preexisting flow of data, with actors such as doctors, test labs and health offices, which by law are obliged to overlook the process.

**Comment by lbarman** [comment]
Hi @pitsch; thanks for your input. We'll keep it in mind should we write a user story.
Closing the issue to try to reduce the number of open comments we need to address...

**Comment by pitsch** [comment]
its ok to keep it closed, as this adresses a major uncertainty. the infection registration law in germany has a recommendation attached which includes a recursive requirement for every matched contact to go for a test. every positive test (which is a registration at the health office) would then practically lead to a list of new registrations of the health office for any matching BT contact. now the caveat: there is an epidemeological interest to get access to the contact list in order to remind those individuals who do not show up for a test. these data flows  are entirely defined by the chain of trust within the health sector (patient, doctor, health office, testlab) which is simply not appearing in your models so far.
