### ISSUE TITLE
typos in the Italian version of the cartoons

### ISSUE THREAD

**Issue by giuper** [DP-3T/documents#212]
one general comment:
the use of "vita" (life) and its plural "vite" sounds a bit strange in Italian. 
"Salute" (health) is more common.
For example the first sentence of the first panel could be: "Proteggere la salute e la libertà"

also, a minor point, in Italian "bla bla bla" seems to be more common than "bla bla".

specific comments:

 **documents/public_engagement/cartoon/it/version_d/panel0002.png**
"siamo contagiosi ~2 giorni" --> "siamo contagiosi per ~2 giorni"

 **documents/public_engagement/cartoon/it/version_d/panel0004.png** 
first row: "trovarle"-->"trovarli"

**documents/public_engagement/cartoon/it/version_d/panel0006.png** 
"interamente" sounds a bit awkard. I would propose "perfettamente", instead or just remove the adverb
"proteggere le vite delle persone E le loro libertà" --> "proteggere la vita E la libertà delle persone"
I guess capital E there is for emphasis; otherwise it should be lower case
aternatively,  "proteggere la saluta E la libertà delle persone"

**documents/public_engagement/cartoon/it/version_d/panel0007.png** 
"invia unicamente un bla bla casuale" what is the intended meaning here?
"it just sends a random bla bla" should become "invia solo un bla bla casuale"
or do we mean that the random bla bla is unique to Alice?
in this case we should say "invia un bla bla casuale che è unico per Alice"

**documents/public_engagement/cartoon/it/version_d/panel0009.png**
 "si scambiano un bla bla unico" --> "si scambiano i loro bla bla casuali unici"

**documents/public_engagement/cartoon/it/version_d/panel0012.png**
"a utilizzo unico" could be removed 
"private" --> "privati"

**Comment by s-chtl** [comment]
Thanks for pointing them out. I forwarded them to the appropriate team.
