### ISSUE TITLE
Optimization opportunity in EphID generation?

### ISSUE THREAD

**Issue by jaromil** [DP-3T/documents#213]
dears, I have a question for the cryptographers out there: after quite some testing I've found out that, instead of processing a long zero octet into AES CTR (ref.impl does `((24*60)/epoch)*16` byte long)  is **much** faster to process a 16 bytes or 32 bytes long zero octet.

since the PRF resulting from HMAC is just 32 byte long, perhaps 32 could be a good length?

or since the EphIDs are 16 byte long, just that?

I'd like to have an opinion if such a change would hinder the cryptographic security of the computation, the advantage is a significant increase in speed according to benchmarks I've done both using software and hardware platforms.

**Comment by FishmanL** [comment]
So, I don't know the in-depth params of the reference implementation, but afaik there should be nothing wrong with using a 32 byte octet for this use case (since AES can handle 256 bit IVs just fine)
