### ISSUE TITLE
Minor issues in the french version of the cartoons

### ISSUE THREAD

**Issue by claustres** [DP-3T/documents#219]
* **cartoon/fr/01.png**: "si nous quarantinons" => "si nous mettons en quarantaine"
* **cartoon/fr/02.png**: "de déjà contenir" => "de contenir déjà"
* **cartoon/fr/03.png**: "avec interrogations" => "par questionnaire"
* **cartoon/fr/08.png**: "compatible (ou la même) que" => "compatible avec (ou la même que)", "5+ minutes" => "+5 minutes"
* **cartoon/fr/12.png**: "aucune intimité n'est perdue" => "l'intimité n'est pas trahie"
* **cartoon/fr/13.png**: "lequel de téléphones proches" => "lequel des téléphones à proximité"
* **cartoon/fr/14.png**: "6 ou + messages" => "6 messages ou +"
* **cartoon/fr/17.png**: "incluiiez" => "incluiez", "du momentqu'elle" => "du moment qu'elle"

**Comment by s-chtl** [comment]
Hi @claustres, thanks for pointing them out. I forwarded it to the appropriate team.
