### ISSUE TITLE
Misleading public engagement cartoon with risk of contributing to unfairness

### ISSUE THREAD

**Issue by pdehaye** [DP-3T/documents#223]
At least two of the cartoons used in the context of public communication around DP-3T are misleading. I do not think at all it is intentional, but do think it is consequential. 
I only found one in this repository though:
https://github.com/DP-3T/documents/blob/master/public_engagement/cartoon/en/panel0003.png
The other is here:
https://twitter.com/ncasenmare/status/1242507368988114944?s=20
These cartoons are misleading in showing a tree out of an infected person while it should actually be a Directed Acyclic Graph (or maybe even a directed graph if multiple innocula matter). While this is possibly justifiable from a public communication standpoint (simplification), the connectivity has profound effect on how digital contact logging tools should be thought of, which itself has consequences on [how incentives are built around their adoption](https://thephilosophyofinformation.blogspot.com/2020/04/mind-app-considerations-on-ethical.html), how they are used, and how ethical and legal concerns are addressed when assessing their proportionality. 
In particular, [this analysis](https://twitter.com/gro_tsen/status/1252581933835575297) might help provide a deeper mathematical understanding of this graph seen as a real graph rather than a tree. Through a double counting argument, the author shows the importance of focusing on reducing the variance of indegrees. 
The diagrams above focus on getting the _average_ outdegree correct, and assume homogeneity (while the  outdegree is clearly heterogeneous across the population, and there has been much emphasis on superspreaders). The distribution of indegrees is completely wrong: they are all 1, with no emphasis on the variance itself. 
This nuance will affect the perception of what should be done with this contact data, if we are to log it, as long as we don't have enough tests or are not aiming for a suppression strategy. This perception will affect risk assessment, data protection impact assessment, public perception and political games around the deployment of those contact logging efforts. It will also affect design specs, which DP-3T might be able to incorporate in the design (or not). 
I would like to offer an alternative use of this contact data here. I do not necessarily think this should be deployed, but want to offer food for thought as an alternative to the current thinking around contact logging, DP-3T and how those protocols should be deployed. 
Reducing the variance in in-degrees should be seen as a purely preventative public health measure, which would inform how confinement measures should be lifted, and where resources should be expanded. 
But if we are going to do this instead, do we really need to collect data? I know my personal indegree is very low, because I spent my last 3-4 weeks on Twitter then GitHub complaining about PEPP's lack of transparency and now DP-3T's lack of responses. But there are people out there who have to work for different reasons, and are exposing themselves to huge risk in doing so ("superspreadee"). This might be for instance Uber or taxi drivers. Maybe these workers should be paid by the state to chauffeur medical personnel around (which would quite plausibly _lower_ the risks to the chauffeur), while their regular clients who physically can should be forced to take public transportation instead. This is just an example, meant to illustrate alternative views on the use of this data.

**Comment by kennypaterson** [comment]
Appreciate your input. As you rightly observe, the cartoons are aimed at increasing public understanding and are not intended, nor expected, to be rigorous portrayals of a graph-theoretic model of the epidemiological situation.

**Comment by pdehaye** [comment]
These cartoons are used to communicate with Swiss citizens. They do have an impact on the public acceptance game played around those apps. Where can I go to have those concerns addressed?

**Comment by kennypaterson** [comment]
I don't think we will be changing the cartoons to depict a directed acyclic graph. I don't think your concerns are valid. If you want to propose something more specific about how the DP3T system should be built, then I would suggest you open a different ticket that is not about cartoons. Issues are easier to consider if they are focussed, specific and actionable.

**Comment by pdehaye** [comment]
@kennypaterson I have previously tried to engage with your colleagues @gannimo and Marcel Salathe on exactly the same issue of the epidemiological inputs you had, but to no avail. 

https://twitter.com/gannimo/status/1252256748544671746?s=20

**Comment by kennypaterson** [comment]
You will have seen that we have had hundreds of issues filed here. We are working on the ones we consider to be of immediate concern to the core DP3T mission. I hope we will be able to deal with the many interesting-yet-complex arguments you are putting forward on a regular basis in due course.

**Comment by pdehaye** [comment]
The issues are broad because the DP-3T collaboration is large. This means I get someone like you (applied cryptographer) speaking outside their expertise and deciding whether downstream concerns I have that touch on the legality and the ethics of the deployment of those protocols when communicated in this way are justified. 

I have left many GitHub issues and tried to make them as precise as I could, but this is a complex interplay of different considerations going into building the whole system (#44 , hey, left completely unaddressed for 16 days now!). 

That is why I am focusing on those cartoons. Myself and the people who do seem to respond to issues (i.e. more technical) do seem to at least agree that they don't quite reflect reality. Whether this subtle point has downstream consequences in fields outside of your expertise should not be your decision. 

Please do pass this on to the right person on your team.

**Comment by kennypaterson** [comment]
My PhD is in graph theory.

**Comment by pdehaye** [comment]
Yes, from the University of London. Mine is in combinatorics and number theory, from Stanford. 

Oh, and while we are at publicly flexing like this, I [left a professor position in Zurich](https://www.thelocal.ch/20180411/how-a-swiss-based-mathematician-helped-lift-the-lid-on-the-facebook-data-scandal) because I thought the use of data by the scientific community was inappropriate. It caused me a lot of problems but I don't regret the end outcome. 

However clever the DP-3T collaboration is, there is information you are not sharing publicly of substantial public concern. EPFL, ETHZ, and many others in DP-3T left PEPP-PT because it was opaque. Please do reflect on this. The whole saga is having profound downstream impact on public health responses across Europe.

**Comment by kennypaterson** [comment]
I was merely responding to your comment implying I was not qualified to comment on directed acyclic graphs. I'm sorry if evidencing my credentials in that respect caused offence. I thought that was what you were looking for.

**Comment by teoli2003** [comment]
Hi @pdehaye 

Sorry you had the impression we are not responsive, this is not on purpose. I'm a (very) recent addition to the community team and still learning who's is doing what, … We are growing our bandwidth to interact with the "outside world" :-)

I can assure you that everybody is working hard to address as many questions/critics as possible. Researchers are extremely busy and have to prioritize problems, and we are trying to funnel issues to the right group. Sometimes it takes some times until they can answer… Feel free to ping an unanswered (i.e. not closed) issue after a week, it may be because it has been forgotten (and the ping will be useful) or because it is not yet at the top of the list.

Keep issues to one topic and as short as possible, it helps us triaging if there are several point raised in one issue, it is likely we will triage according one of them, and the others will be lost.

A few last bits:
- keep it civil (you have!) in any case
- not all issues/arguments will be "won" (this is normal, sometimes just because it is not the right moment)

Thanks for your help, we hope to be more responsive in the future.

**Comment by pdehaye** [comment]
@kennypaterson I will take the outcome here as constructive. At least we agree that the graph is not an accurate representation of the epidemiological modeling that might be going on behind the scenes, but we disagree on what action to take as a consequence. 

I say that this graph could be misleading for others outside of DP3T trying to interpret the _ultima facie_ consequences of the roll out of such a system to fight COVID, even when everyone internal to DP3T is very wary of doing the right thing.

**Comment by pdehaye** [comment]
Hi @teoli2003 

You can see the list of the outstanding issues I have raised [here](https://github.com/DP-3T/documents/issues/created_by/pdehaye). 

You will see that they date from 19 (!), 19, 17, 17, 17, 14, and 3 days ago. Those are the issues still open. You will see that they are classified as touching on one topic, which is _legal_ (at least according to you). 

The world is not simple. It is a trope that engineers are focused on solving a problem and failing to see the broader consequences of their work. In this particular case, that means you can't formulate the one perfect GitHub issues that will address the problems as chunks comestible to engineers. 

It's a complex thought process on my side of explaining why DP-3T's specs were wrong - or rather that the urge to deploy that system in Switzerland to me seems unjustified and prone to failure in adoption, or will come at huge expense that would have been better spent early re-assessing the specs you were given. 

As explained right above, I will take the outcome of this thread as constructive. 

Thank you for stepping in and cooling things down.

**Comment by pdehaye** [comment]
I would like to point folks here to the issue [here](https://github.com/digitalepidemiologylab/swisscovid_efficacy/issues/4), and also corresponding issues at that repository. 

In short: now that we are moving into operational phases, the concerns expressed originally in this issue as a very theoretical matter are coming more and more to the surface. While there is no evidence at this stage that digital contact tracing apps would be discriminatory, there is real reason to think that the most obvious metrics that could be used to assess their efficacy or encourage their use would precisely hide if not amplify any discriminatory impact. 

**Disclaimer: This is my personal opinion, and does not necessarily reflect the opinion of any of my employers or clients.**

**Comment by pdehaye** [comment]
Further up this thread, I focused on the variance of indegrees and consequences thereof.

Please find a relevant update on the matter from _Nature Communications_, titled _The counterintuitive implications of superspreading diseases_.

https://www.nature.com/articles/s41467-023-42612-9
