### ISSUE TITLE
rejection of EphIDs from a seed after it was known to be disclosed

### ISSUE THREAD

**Issue by dirkx** [DP-3T/documents#228]
Would be good if the paper stressed that clients should pre-actively ignore any EphiID received of seeds they have seen as known-infected (or, if there is an earlier date with them; from that date onwards).

As to avoid a stuffing/faking attack (https://github.com/TCNCoalition/TCN/issues/61).

**Comment by Vanuan** [comment]
I think this line implements the requirement:

https://github.com/DP-3T/dp3t-sdk-android/blob/ba4f2557738efbf13e677d8af48d477b53d1963a/dp3t-sdk/sdk/src/main/java/org/dpppt/android/sdk/internal/crypto/CryptoModule.java#L196

**Comment by lbarman** [comment]
Hi @dirkx, @Vanuan, this has been added in the whitepaper, stay tuned for the next version :) thanks a lot !

**Comment by Vanuan** [comment]
There's also this malicious/activism attack:
1. A group of privacy preoccupied users decides to use the same key
2. When any of them becomes diagnosed, he enters TAN code to the database
3. Now the database is contaminated with fake contact events

I think this a primary reason why BlueTrace / OpenTrace decided to centralize the issuance of keys.

**Comment by dirkx-reno-2020** [comment]
@Vanuan given 1) the size of the space - I do not see how this would work ? And 2) most implementation profiles/approaches use a random tan; so that is not an issue either ?

Could you elaborate ? And/or if needed re-open the ticket ?!

**Comment by Vanuan** [comment]
@dirkx-reno-2020 I think this is related, but somewhat different.

> 1) the size of the space - I do not see how this would work

Let's say there's a significant amount of activists, who actively oppose contact tracing (for example, in countries where the usage of the tracing app is mandatory). Let's assume the opposition is so broad that there's at least one such user in an area a lot of people frequently visit (a shop/market).

They modify the app to look the same (to comply with the law) but work differently.
The modification ensures that ephID that is broadcast is the same for any device it's installed on, not random.

Eventually, one of the activists become infected and receives a legitimate TAN code. He legitimately enters it to the remote database. Let's assume that there's a limited number of remote servers, so there's at least one infected activist per server.

After the TAN code is verified, a key is entered to the database.

At this point, most of the users receive an alert "you've been exposed", even though there's no guarantee that all activists are infected.

**Comment by dirkx-reno-2020** [comment]
@Vanuan ok - so that results in a lot of identical ephid's in people their lists. Now how would they get their seeds (more than once) into the confirmed-infected queue ? 

Or are you assuming that the medical authorities issue the TAN disconnected from the phone - and someone can then approach the submission API with the seeds and that TAN ? So effectively in your scenario a TAN is a 'fine to upload the 8 bytes (or 14x8 bytes for GACT/PACT, etc)' permission ?

In the processes I am familiar with - the TAN is generated on the phone and part of the submission process. Would that not require fully rooted-phones; with modified real code at a large scale (i.e. well beyond what you could do with an enterprise-signature to bypass the appstore) ?

**Comment by Vanuan** [comment]
@dirkx-reno-2020 
> Now how would they get their seeds (more than once) into the confirmed-infected queue ?

Basically, I'm asking what prevents seeds from being identical?

**Comment by Vanuan** [comment]
> So effectively in your scenario a TAN is a 'fine to upload the 8 bytes (or 14x8 bytes for GACT/PACT, etc)' permission ?

Does it even matter how TAN code is generated? There is a legitimate way to enter it.

**Comment by Vanuan** [comment]
> In the processes I am familiar with - the TAN is generated on the phone and part of the submission process. Would that not require fully rooted-phones; with modified real code at a large scale (i.e. well beyond what you could do with an enterprise-signature to bypass the appstore) ?

I'm not sure what you're talking about. Are you assuming that medical authority has a full control over people's phones and can somehow validate whether an app is legitimate? Or you're assuming that it would be hard to install an app if it's not in the store? Maybe it's the case for the iOS devices, but not for Android, which can be rooted in several taps.

**Comment by dirkx-reno-2020** [comment]
@Vanuan yes - as it lives (assuming checksum, 10 digits, not using 0, 1, O etc) in a 40-50 bit space; and needs to either come from a legit (apple, google signed) app, an enterprise signed fake/doctored app (few 100-low 1000) or run on a sufficiently rooted phone  that is still able to submit the seeds to the existing infra* AND of the latter two groups you need to have sufficiently large volumes in your society (or repeaters, hacked public-transport turnstiles, etc).

So we need to make sure that we get **exactly one** of those in the submission for testing queue (more than one would be detected - assuming we're not having things like detection in the field) & wait for the medical process to enter the TAN of this seed which has generated bulk EphIDs (i.e. patient was infected).

*) I am assuming that the TAN simply matches the seeds submitted HMAC; as if you've already hacked the app to that extent - adding things like that is easy.

The scenario which would worry me more is that of a few likely infected people providing their EphIDs  from legitimate phones of that day/hour to a network of people who broadcast them where-ever they can (skipping over GACT here) nation wide with something that does not really need to run in the walled/controlled gardens of apple or google - but, say, on an ESP32 with a solar panel.

**Comment by Vanuan** [comment]
Yeah, you could place a set IoT devices in high traffic places which would gather EphID and re-broadcast them elsewhere.

Can't think of a way to protect against the repeat attack. Maybe ephID should have some sort of a precise timestamp signed by a timestamp server.

Well, that all seems a bit too theoretical.

**Comment by dirkx** [comment]
Not overly theoretical in countries (like NL) where there are both activist and highly centralised infrastructures that can do such broadcasting from a few nexuses.

FWIIW - I do think these things are important; and still think it is a shame that the ZKP aspect was removed from the protocol very early on. That helps exactly with this.
