### ISSUE TITLE
Is 14 days enought?

### ISSUE THREAD

**Issue by gscokart** [DP-3T/documents#23]
If I don't have symptoms, I may contaminate people.  When the people that I contaminated will be sick, tested and will finally report their sickness.  At that time, I will be detected as being at risk, I may be tested positive (or have the anticorp)

In that case, wouldn't it be very helpful to have a longer history so that the other persons that I may have contaminated earlier (that are maybe also asymptotic) can be informed that they are also at risk and should be tested?

An other reason to have longer period is if I'm still contagious longer than 14 days.

**Comment by gscokart** [comment]
https://rega.kuleuven.be/if/tracing-tools-for-pandemics (from KUL) mention at least one month of lookback time.

**Comment by timoll** [comment]
There is a point of diminishing returns. 

You are more contagious the closer you are to having symptoms. It is also much more likely that you were infected 2-7 days ago than 7-14 days ago.

I think this is a decision that has to be made by health authorities as it is a trade off between number of quarantined people and missed infections.

**Comment by s-chtl** [comment]
Hi @gscokart and @timoll, thank you for your inputs. 14 days is the reference duration used throughout the paper for consistency. We are actively discussing with epidemiologists and expert to fine-tune it further. We would update the whitepaper if this changes.
Thanks again and I hope this helps clarify the issue.
