### ISSUE TITLE
Interoperability, Metadata and Source Tracing

### ISSUE THREAD

**Issue by ChristianRomberg** [DP-3T/documents#237]
Hi.
As far as I understand, in the current protocol specifications at most a single bit of information can be transferred. It remains to be seen, but I doubt a single bit will be sufficient for practical purposes.

In the Dutch "appathon", it was said that the GGD (Dutch health authorities) would also do "source tracing", meaning they'd try to find out who a person was infected from. I think that in the current version protocol versions, implementing source tracing would be challenging.

A different (related) problem: Every country has different testing capabilities, different requirements and therefore different approaches when it comes to fighting the ongoing pandemic. Consider a country with poor testing capabilities; a symptom reporting mechanism might be more feasible than a "health authority spam filter". How would interoperability between countries with differing approaches look like?

These problems could be solved by incorporating metadata into the reports.

Have you considered incorporating metadata into your protocol? If so, what where the reasons for deciding against it?

**Comment by s-chtl** [comment]
Hi @ChristianRomberg, thank you for reaching out. We are actively discussing with epidemiologists to address those concerns. As a rule of thumb, we tried to keep the amount of data exchanged to the minimum required to fulfill the functional requirements and still provide good privacy levels. Sharing metadata or more information might result in leaking social-graphs and damage users privacy. You can have a look at our documents about security and privacy in the "Security Analysis" directory  for more information.
I hope this answers your question.
Best,

**Comment by timoll** [comment]
There is only a single bit of information given to the user. Signal strength and duration of a contact are available to the app.

Has it been considered to give users access to shareable data once they get infected? 

There might have been a contact that was either determined to be too far away or too short for quarantine. How often this happens might be important for epidemiologist. It might also help manual contact tracers as well.
