### ISSUE TITLE
Possible data privacy enhancement

### ISSUE THREAD

**Issue by umiddelb** [DP-3T/documents#244]
Hi,

I've read through the current issues in order to see if someone else has already written down the same idea. 

As you are not looking for specific individuals but for contact situations where a (later) diagnosed patient is involved, what about uploading not just the (i, seed_i) for the patient, but H(EphID_patient || EphID_contact), for all relevant contacts, or even H(Proj(EphID_patient) || H(Proj(EphID_contact)), where Proj() is a projection, discarding some parts of information in a deterministic way.

This means that the Cuckoo filter entry is calculated on the mobile device itself and not on the distribution server.

A possible "camera attacker" has to broadcast his own EphID as well, otherwise he or she won't be able to track a patient. He or she cannot stay completely calm in order to disguise an individual.

This approach has of cause some downsides. e.g. higher traffic volume and more entries in the Cuckoo Filter. And a lot more, which I'm not aware of.

**Comment by lbarman** [comment]
Hi @umiddelb, thanks for the input! In general we upload nothing about contacts, as this reveals graph information (also see [P1](https://github.com/DP-3T/documents/blob/master/FAQ.md#p1-why-dont-infected-users-upload-the-ephemeral-bluetooth-identifiers-ephids-they-have-observed-to-the-backend-server-so-that-other-apps-can-download-them-and-check-for-contacts-locally) in our FAQ), even if what you suggests makes the task harder for an adversary (problem is: we can't tell in advance if "harder" is good enough). As you mention, there are also concerns about compactness.

Would this answer the question?

**Comment by timoll** [comment]
There is proposal #66 that would achieve the same thing over ECDE key exchange. If you just Hash the two EphIDs, anyone that listens to both parties can calculate H(EphID_patient || EphID_contact). So it would not protect against passive identifying attacks. 

Because a passive listener can determine the Hash of two contacts, it could identify the contacts of infected persons with this proposal. This would not be possible with ECDE key exchange.

ECDE keys can also be used as EphIDs should the compactness become a problem, I proposed this in #231

**Comment by umiddelb** [comment]
> ... 
> Would this answer the question?

Thank you very much for taking your time to make up an opinion. I thought that the value H(Proj(EphID_patient) || H(Proj(EphID_contact)) would be exclusive for the patient's and the contact's phone, but it isn't. 

Introducing some information which is by protocol design exclusive for these two phones only (like a DH key), this was my intention. In this setting, an adversary cannot stay calm and just passively collect information in order to reveal information.

**Comment by umiddelb** [comment]
Hi @timoll, 
 
> This would not be possible with ECDHE key exchange.
I totally agree, this is the part of information I was looking for. You unlink the information which is broadcasted on local scale from the information published in the public, but you are still able to track a contact situation, but on the contact's smartphone only and nowhere else.

There is still the challenge to distinguish a legitimate user from an adversary if they both use the contact tracking app or at least "speak" the proximity app protocol appropriately. But this is a different task.

**Comment by lbarman** [comment]
Hi both, thanks for the inputs.

> Introducing some information which is by protocol design exclusive for these two phones only (like a DH key), this was my intention. In this setting, an adversary cannot stay calm and just passively collect information in order to reveal information.

In this case, let's continue the discussion on DH here https://github.com/DP-3T/documents/issues/66 :)
