### ISSUE TITLE
is there a DP3T logo?

### ISSUE THREAD

**Issue by dret** [DP-3T/documents#257]
hey team!

i just produced a an overview video for contact tracing apps (https://www.youtube.com/watch?v=SZIKVqGC-kA) and my goal is to produce much more content soon, because i think that people will look for more information about these apps. i used the PEPP-PT logo and just used the apple/google from their site, but i could not find a DP3T logo. do you have one? 
if not, i think it would be really useful to have one. noting magic required, but it helps a lot with communications. if nobody has time on your side and there is at least potential interest, let me know and i will happily play around with some ideas and maybe there is one you like.

thanks and cheers and keep up the good work!

dret.

**Comment by timoll** [comment]
It's in the repo:

https://github.com/DP-3T/documents/blob/master/graphics/logos-dp3t/logo.jpg

**Comment by dret** [comment]
On 2020-04-30 16:17, Timothée wrote:
> It's in the repo > 
https://github.com/DP-3T/documents/blob/master/graphics/logos-dp3t/logo.jpg

sweet, thanks a lot! maybe use it on your documents: it's pretty and 
it'll make sure you're building a bit better brand recognition. thanks 
again!
