### ISSUE TITLE
Discard GPS and use serving mobile network MCC

### ISSUE THREAD

**Issue by ChrisDaumer** [DP-3T/documents#26]
In order to get the country location, use serving mobile network MCC information instead of using GPS. To do that the handset only needs to be connected to the mobile network. 

You will save battery and remove privacy concerns about geolocation.

**Comment by jeffallen** [comment]
Nearby in the white paper is says "these backends can be hardcoded in the app".

I propose instead that the app should download some kind of configuration file saying, "when you are in this region, this is the backend that covers you". With a fallback to a global backend operated, in a neutral country, perhaps sponsored/authorised by WHO.

In general, this question of interoperability and federation will be very difficult and it will be more important to get something running at all than getting something perfect.

**Comment by carmelatroncoso** [comment]
Thanks! These comments make a lot of sense. Integrating them in the next version!
