### ISSUE TITLE
Falsche Alarme bei Ärzten

### ISSUE THREAD

**Issue by medicus-lost** [DP-3T/documents#265]
wie verhindere ich falsch positive Alarme als Arzt der Covid Abstriche unter Schutzmassnahmen durchführt? Auf das Handy kann während der Arbeit nicht verzichtet werden. Ist eine passagere Deaktivierung der App vorgesehen? Könnte ein Standort eingegeben werden an dem die App automatisch deaktiviert um zu verhindern, dass die App am Arbeitsplatz läuft und dort Kontakte registriert. ( Werden alle meine Patienten in Quarantaine geschickt, wenn ich einen Patienten teste, der positiv ist?)

**Comment by AndreasHuber-CH** [comment]
Soweit ich das beurteilen kann, haben sie jederzeit die Möglichkeit das Tracking in der App temporär auszuschalten, oder temporär Bluetooth auf ihrem Telefon ganz zu deaktivieren. Das würde in Ihrem Fall sicher Sinn machen, da sie sich während der Arbeit ja anderweitig schützen.

Weiter, wenn sie mit einem Patienten Kontakt haben der positiv ist (und sie das Tracking an lassen), würden sie selbst von der App informiert werden, nicht aber ihre anderen Patienten. Erst wenn sie selbst als positiv eingeschätzt werden und sie in der App den covid-code eingeben werden Leute benachrichtigt, die sich in ihrer Nähe aufgehalten haben.

**Comment by MarkoSchuetz** [comment]
Ich würde hierfür Apps wie Automate (Android) in Betracht ziehen.

**Comment by kollokollo** [comment]
Isnt this exactly what we want: Inform all patients, if their doctor was infected? 
Remember:
Chancelor Merkel also went into quarantaine, because her doctor hat contact to an infected patient.

**Comment by medicus-lost** [comment]
ja, wenn ich positiv bin bleibe ich zu Hause, auch wenn ich als HCW eigentlich dennoch arbeiten dürfte. Da ich aber beruflich täglich Kontakt ()
