### ISSUE TITLE
[Improvement] Getting rid of push (FCM/APN)

### ISSUE THREAD

**Issue by laryllian** [DP-3T/documents#29]
In the current draft during the process of contact tracing (4. in the DP&S doc) new EphIDs of infected ppl would be pushed from backend to clients regularly, this however is the only use for push and therefore the only reason to involve Google's FCM / Apple's APN, right?

Why not rather use a regular diff-based direct pull mechanism and therefore cutting out the third actors (especially those actors)? Since only static EphIDs are being used, load issues should be solvable. In addition: The app could be FOSS and truly libre software. :)

Any comments?

**Comment by madhavajay** [comment]
@laryllian the usual reason to use things like FCM / APN is that they are able to push to the device when a normal app does not have background access to make network requests to load new data. This is especially true with iOS. Obviously it's not a true push, iOS is polling Apple's servers but it does this intelligently in a privileged manner.

**Comment by gajeam** [comment]
The EphID doesn't have to be sent through the FCM/APN push notification. The push could be used to wake the app up and then the app could call the backend to get a new EphID.

**Comment by madhavajay** [comment]
@gajeam absolutely that is almost always what would happen anyway. As you are pointing out, the APN / FCM system is really just a standard protocol for notifying a mobile app of an update for which it should awaken and fetch itself directly.

**Comment by MasterEmit** [comment]
@madhavajay Big question is, "notifying a mobile app of an update" means that the server itself should be aware, that an update for a specific app on a specific device exists. Or do you want to trigger push notifications on a regular base to all devices? If not we get meta data about a specific device and why it was informed.

**Comment by madhavajay** [comment]
Depending on the needs of the app and foreground usage for types of bluetooth scanning it could be beneficial to send a visible alert to encourage users to open the app, but generally speaking these updates would be part of a silent push. The brute force way might be just to send these periodically and slightly randomly so that the devices don't DDOS the server when calling for updates, but this could also be based off the last known phone home time (and update) from the device itself.

**Comment by jorants** [comment]
I think the main point is that these push notification protocols are not FOSS. In the case of android they are not part of the OS (Which is open source) but of google play services (which is not). See also the relevant discussion around the FOSS version of telegram: https://github.com/Telegram-FOSS-Team/Telegram-FOSS/blob/master/Notifications.md 
You can get around this by constantly showing a notification that the app is running, allowing you to stay on in the background, which might be needed anyway for the BLE.

**Comment by lbarman** [comment]
Thank you all for your inputs!
Naturally, we try to minimize data exposure to the fewest actors. In this case the downloaded data is public; if Google/Apple want it, they just install the app and get the data like any other user.
Whether we can implement the push/download in a FOSS fashion (without FCM/APN) is a different question, I'd prefer FOSS alternatives too but this choice has several constraints (timeline, compatibility, etc).
Does this answer the question ?
