### ISSUE TITLE
Why does an infected patient pick a new​ completely random key?

### ISSUE THREAD

**Issue by rouvoy** [DP-3T/documents#33]
The [DP-3T white paper](https://github.com/DP-3T/documents/blob/master/DP3T%20White%20Paper.pdf)  mentions that «_After reporting their current ​SK_t , the smartphone of the infected patient picks a new completely random key._» (bottom of page 7).

By doing so, do you accept that infected patients to take a new identity, without being advertised as infected?

I understand that, upon a positive infection diagnosis, the patient can share her/this _secret key_ (SK) with the server to notify at-rist citizens. But, what happen to the infected patient and her/his app from there?

Some of them will have to stay at the hospital, thus having controller interactions with the rest of the world, but others can also stay confined at home, depending on their symptoms, if benign. The latter might therefore remain indirectly in contact with other citizens, even if the confinement procedure aims at reducing the risk.

By automatically regenerating a new SK, this means that, after reporting the  current SK_t, the infected patient cannot be tracked, but she/he won't be detected by others before eventually uploading the new SK at some point in the future.

I was therefore rather thinking of keeping the same SK as long as the patient remains infected, by replacing the SK_(t-1) with the current SK_t by the end of the day, to keep detected potential at-risk new cases, and rather introducing an official procedure that allows, through an authorization given by the practicians (_e.g._, a qr-code), the patient to generate a new secret key after being officially claimed as _recovered_ from COVID-19, and therefore not presenting any danger for others. This can also be used to remove the former SK from the server after some days.

**Comment by amalic** [comment]
I guess the idea is that users can not be tracked. A new key must be in no relation to an existing key. But once data is being uploaded to a central repository, it's eqsy to aggregate all random keys to a certain user.

**Comment by rouvoy** [comment]
In such a case the new SK should be reported to the central server on a regular basis, as long as the patient app keeps sharing EphIDs with others.

**Comment by carmelatroncoso** [comment]
Thanks for the comment. We realize we have not been clear about the scope of the app.

Once infected patients report themselves, the app does not attempt to track them, nor does it provide a mechanism to ensure that they follow medical orders. Recall that the goal of the app is to avoid asymptomatic users unknowingly spreading the disease. Diagnosed users are assumed to be responsible and take precautions when they go to the street, for instance to a doctor appointment. We do not attempt to prevent misbehavior. The reason being that the gain in utility (one irresponsible person being under control) does not justify the loss of privacy for other well-behaved infected users.

This will be added to the next version of the white paper.
