### ISSUE TITLE
Add a license

### ISSUE THREAD

**Issue by nemobis** [DP-3T/documents#4]
This repository is currently proprietary, so no collaboration is possible. Please add a free license statement. The PDFs contain a "CC-BY 4.0" note so it's easier to align to that.

**Comment by kennypaterson** [comment]
There is no codebase for you to contribute to yet, but there will be soon. At that point, we will add a detailed licence statement. Our intention is to be as liberal as possible in this regard. Please bear with us.

**Comment by pierreozoux** [comment]
I see that this repo: https://github.com/DP-3T/dp3t-sdk-backend
has MPL License, great :) .

But the documents repo doesn't have a license which means it is proprietary.

A minor detail, that you probably just forgot, but I still think that this is important, hence my comment.

**Comment by BartKoppers** [comment]
Agreed. Did a PR previously, adding CC BY-SA 4.0

https://github.com/DP-3T/documents/commit/dcb9150195bc0f094bf6f19810cd307cccbd2b8c

Issue was closed with remark: “we know, have to decide “

Alas...


Op wo 22 apr. 2020 om 14:45 schreef Pierre Ozoux <notifications@github.com>
