### ISSUE TITLE
Data-protection-relevant actor missing: Mobile Network Provider

### ISSUE THREAD

**Issue by sebastianbuettrich** [DP-3T/documents#42]
The list of 
"five main data-protection-relevant actors in this system:
1/ users
2/ health authorities
3/ backend server
4/ epidemiological research projects
5/ mobile phone operating system providers"

is missing an important actor in this system,
the mobile network provider.

Mobile network provider data are - apart from the mobile phone itself -
the richest source of identity, network activity and location data,
and frequently used, in both legal and illegal ways, to correlate datasets,
e.g. by entities that the operator is obliged to share data with.

(see e.g. recent legal/tech case in Denmark, Teledatasag - need to find english source ..)

A sub-issue arising from this seems to be the fact that
specific network activity is triggered by infection events.
Such network activity will be relatively easy to detect and personalize.

While encryption can provide protection against full eavesdropping,
the fact that the very occurrence - not the content - of network activity implies an event
makes the event trackable.
(This is an identified attack vector against smart meters and IoT units.)

(Service providers are mentioned in the White Paper, under "Eavesdropping" -
which is not what this issue is about.)

**Comment by maskeeter** [comment]
@sebastianbuettrich I think this will apply only on upstream events i.e: contact EphIDs sent from infected user's phone to server. for downstream events all devices will be treated equally, as I understood from the below paragraph:
> The server transmits information about new infected ephemeral identifiers to users’ phones, which compute infection risk ​locally.

**Comment by snakehand** [comment]
One mitigating measure could be to let the app have a configuration option : Use wifi only / Use mobile data after X hours.( In this scenario the client actively pulls the list of infected SKs )

If the default setting is to only use mobile networks for data transfer after 6 hours for instance, the amount of data visible to network operators should be greatly reduced.

Also if the list of infected SKs is digitally signed, they can be served in a more distributed manner, making traffic analysis harder.

**Comment by sebastianbuettrich** [comment]
@maskeeter   yes, it s the upstream events that would be the concern, as they - if i understand this right - would only occur, or look significantly different, in an infection case.
@snakehand - this could mitigate the problem to some extent, but trying to move this kind of app away from mobile networks probably is not a feasible strategy.

**Comment by lbarman** [comment]
Thank you all for your inputs.
We agree; we considered ISPs as eavesdroppers. I'm not sure I fully get your comment:

> (Service providers are mentioned in the White Paper, under "Eavesdropping" -
which is not what this issue is about.)

If your point is "ISPs have large datasets which they can use to de-anonymize what they see/eavesdrops", this is why we make sure that all eavesdroppers (as described in the white paper), including ISPs, see minimal information.

>While encryption can provide protection against full eavesdropping,
the fact that the very occurrence - not the content - of network activity implies an event
makes the event trackable.

absolutely, this is traffic-analysis, and we included it in our risk analysis (notably it is thwarted by dummy uploads).

Would this answer the question ?
