### ISSUE TITLE
Probability of success and achievability missing as key criteria for validity of proposal 

### ISSUE THREAD

**Issue by pascalwhoop** [DP-3T/documents#46]
First of all great work. Very European way of tackling this problem. :+1: 

A core thing I missed in the white paper is the **success probability of this project setup**. A naive implementation (track all users, store all data centrally and allow scientists to operate on data) has resilience towards design mistakes. All data is still available. Analysis such as tracking gaps, errors etc can be done retroactively. 

In this design, the developers and operators of this system have very little insight into the effectiveness of the system. (Keyword Metrics). What if the apps happen to be terminated by the OS and stop recording IDs for a few hours? These interactions would simply be lost. No one would know. What if regional differences in culture and mentality lead to increased downloads / refusal to do so? 

In short, while in a perfect world, this setup _should_ allow individuals to be informed about their risk, it keeps authorities and operators completely blind. How is a country supposed to decide on policies if they don't know how many risky interactions have been recorded? 

What is therefore missing in this proposal are **reasonable metrics**. While the privacy and security of the citizens is of importance, so too is **the ability as an operating institution to confidently claim that the system is working or not**. Without insights into the systems operations, this is hardly possible. 

## Recommended metrics (to be expanded)

- number of IDs recorded / day
- metrics about app FCs or app not running in background for periods of the day
- offering users to share extended data that may identify them to support developers in evaluating system operations

## Expectable error scenarios

- 2 users should have recorded each other's IDs (because it is know that they have been in proximity) but the phones did not record this. Why?
- Phone OS or scheduler may terminate process due to low memory. Can we detect this and mitigate it through software changes? 
- Subregion of country sees low number of risky interactions. Why? Low infection rate? Low interaction rate? Low installation base? Thick walls?

**Comment by pdehaye** [comment]
Note: this is a necessity for the legal analysis to be complete.

**Comment by lbarman** [comment]
Hi @pascalwhoop, thanks for the great feedback; indeed it would be desirable that the institutions/governments have a feedback loop to check whether the system works or not. Some of the metrics they would have access to (with the proposed design) are, per individual getting tested, whether they were declared healthy/at risk by the app, and if they were using the app at all. Assuming an individual gets tested in its own region, this also gives high-level statistics about adoption rate/usage per region.

> 2 users should have recorded each other's IDs (because it is know that they have been in proximity) but the phones did not record this. Why?

In practice, we'll how well the Bluetooth part of the contact-tracing works, but for sure the channel is lossy and some contacts will be lost.

> offering users to share extended data that may identify them to support developers in evaluating system operations

Do you mean some kind of functionality to "upload usage data" that would help developers ? Could be a good idea (although tricky to do in a privacy-preserving way)

> Phone OS or scheduler may terminate process due to low memory. Can we detect this and mitigate it through software changes?

and
> metrics about app FCs or app not running in background for periods of the day

If you have an insight on how to do so, feel free to comment, I'll forward it to the dev team (they are aware of the issue). 
Thanks!
