### ISSUE TITLE
Add recomendations about open-source or not

### ISSUE THREAD

**Issue by gscokart** [DP-3T/documents#48]
Althought it is maybe not a technical aspect (and maybe out of scope of your design), the way the app and the server application is developed might have an impact on the adoption.

It could be usefull to have an expert advice on whether the application should be developed in opensource.

I guess some people will trust it more if it is open sources, and other would trust it less.  I don't know on which side will be the majority.

**Comment by marado** [comment]
According to https://noyb.eu/en/data-protection-times-corona (and I agree):

> People must be able to trust technology in the fight against the coronavirus, so that enough people will participate. This can be achieved by measures such as good data encryption, storage of data within the user's phones and the publication of the source code ("open source").

**Comment by pascalwhoop** [comment]
It was my understanding that a reference application will be developed which I’d assume would also be open source?

**Comment by jaromil** [comment]
For those interested, here a walk-through of a free and open source implementation (using Zenroom) of the crypto inside DP-3T (pending review) https://medium.com/@jaromil/decentralized-privacy-preserving-proximity-tracing-cryptography-made-easy-af0a6ae48640

**Comment by snakehand** [comment]
I started implementing the crypto in Rust here https://github.com/snakehand/dp-3t-client - it is not compatible with the medium / Zenroom code yet , but I will make some adjustments to make it interoperable.

**Comment by marado** [comment]
More info about the need of having the implementations be free software:
https://fsfe.org/news/2020/news-20200402-02.en.html

**Comment by kkoenen** [comment]
Very much in support of OP. To make it a little more technical; what are the available best practices to verify (possibly at run-time) if a packaged iOS / Android app is based on a certain version of the published source? Or is 'verified publisher' the best horse to bet on wrt application integrity?

**Comment by koenvervloesem** [comment]
@kkoenen The [Reproducible Builds](https://reproducible-builds.org/) project is a set of software development practices that create an independently-verifiable path from source to binary code.

**Comment by jaromil** [comment]
Zenroom is a (FOSS) portable, isolated and deterministic execution environment of 1MB payload approx whose bytecode can be signed and versioned: it solves the problem when adopted for internal crypto and business logics.

**Comment by snakehand** [comment]
dp-3t-client ( https://github.com/snakehand/dp-3t-client ) is FOSS portable Rust implementation. Rusts safety guarantees lowers the auditing burden, and a high level C library API is provided for interoperability. Rust also offers reproducible builds.

**Comment by setpill** [comment]
@gscokart 
> I guess some people will trust it more if it is open sources, and other would trust it less. I don't know on which side will be the majority.

Why would people trust something less if it's open source?

**Comment by nicorikken** [comment]
[A similar statement](https://www.veiligtegencorona.nl/) has been released in the Netherlands, signed by prominent civil rights defenders. In section 3:

> De broncode van de applicatie en de overige infrastructuur is **openbaar onder een vrije software licentie**, zodat iedereen de werking van het systeem kan controleren.

Translates to:

> The source code of the application and the other infrastructure is **public under a free software license**, so everybody can check the workings of the system.

**Comment by gscokart** [comment]
I'm usually in favor of opensource application, and I would personnally trust it more.  
In this context, the major threat is a fork of the app.  An that is much easier in opensource (ok, a mobile app is still easy to clone/modify).  So I suspect even security specialist will have hard debate on the subject.

But at the end, seeing the urgency (and the limited time for education), it doesn't matter what the security specialist think, nor what IT geek think.  What will matter is what journalists says, and what majority of non it people will trust better (and that, I don't know what it is).
