### ISSUE TITLE
Assess existing software and systems

### ISSUE THREAD

**Issue by nemobis** [DP-3T/documents#5]
At some point it will be nice to assess the main apps among those which mushroomed in this period, against the best practices as defined in the documents. NOYB has a nice wiki page with a growing list:
https://gdprhub.eu/index.php?title=Projects_using_personal_data_to_combat_SARS-CoV-2

**Comment by kennypaterson** [comment]
Thanks. We are keeping an eye on parallel efforts and are in touch with many of them, sharing expertise and ideas where we can.
