### ISSUE TITLE
Cash

### ISSUE THREAD

**Issue by burdges** [DP-3T/documents#51]
Apologizes for this being way off topic, but it appears this repo acts like the broad discussion area right now.  

A priori, I'd expect that people abandoning cash broadly weakens herd immunity.  If anyone studied this question, then maybe worth noting that work somewhere.  

At the same time, there are more people avoiding cash in favor of electronic payment schemes, due to the corona virus, which may even be warranted.  There are no currently deployed electronic payment system with both good scalability and meaningful privacy.

Among the blockchain designs, there are deployed schemes like ZCash with strong privacy, but that run into typical blockchain scaling problems.  We expect their scalability to improve, but not within the next year.  There are numerous blockchain "layer two" designs like lightning, but afaik those with working code provide zero privacy.  These may improve privacy over the raw blockchain, but their privacy remains roughly like credit cards.

There exists an older simpler technology for private payments called blind signatures that works well with fiat currencies, but not so well with blockchains.  GNU Taler provides a relatively mature implementation for all components:  https://taler.net/en/  

I'd expect Taler could be deployed in only a couple months if pushed, although I emphasize that maybe the easier options should simply be convincing people that cash remains safe enough.

**Comment by kennypaterson** [comment]
Thanks for this comment. We'd like to focus discussions here on the DP-3T proposal rather than the broader issues this comment touches on. So closing it now as an issue.
