### ISSUE TITLE
Unclear statements about reporting of at-risk status to the health authority

### ISSUE THREAD

**Issue by throwException** [DP-3T/documents#52]
To my understanding it remains unclear, if the app upload at-risk status to the health authority and and if this upload is voluntary or not.
* On page 10, Security and privacy considerations, Threat model, Health authority, the paper states that the health authority only learns of at-risk individuals if the reach out themselves, which I took for a notification outside of the app.
* Then on page 12, Privacy, Privacy Analysis, At-risk individuals, it states that the app relays at-risk status to the health authority without mention of user consent.

From a acceptance standpoint I think this is a very important point to clarify, as people will be reluctant to install an app that report their risk to the health authority leading to them spending time in enforced quarantine. From a freedom standpoint there is a stark difference between self-imposed and state-enforced quarantine.

**Comment by bdsl** [comment]
https://github.com/DP-3T/documents/issues/32 is related.

**Comment by carmelatroncoso** [comment]
Thanks for this comments! We will fix the contradiction in the next version.

To be clear, there is no automated notification to the health service, but a local notification that recommends the user which actions he/she should take.
