### ISSUE TITLE
Use GNUnet as decentaliced, anonymous data transport

### ISSUE THREAD

**Issue by htgoebel** [DP-3T/documents#53]
For solving the issues of both central storage and non-anonymity due to IP-addresses, GNUnet could be used:

>  [GNUnet](https://gnunet.org/) is a new network protocol stack for building secure, distributed, and privacy-preserving applications. With strong roots in academic research, our goal is to replace the old insecure Internet protocol stack.
>
>  GNUnet is […] run as an overlay network on top of the existing Internet infrastructure forming the basis of a hybrid peer-to-peer mesh and relay backbone for applications to run on.

AFAIK GNUnet uses distributed hash tables for finding both peers and data. Please get in touch with the GNUnet project to evaluate how to work together. Thanks.

**Comment by kennypaterson** [comment]
Thanks. We've decided not to use mixnets or similar technologies in our approach due to additional complexity and limited added privacy that they offer. Please see our FAQ, P5.
