### ISSUE TITLE
Public IPv4 addresses are not unique

### ISSUE THREAD

**Issue by obi458** [DP-3T/documents#54]
If the backend server only listen on IPv4 addresses, the uploader is not unique and therefore anonymous!

**Comment by pevab** [comment]
Not that easy. Phone public ip, even ipv4, does not change that much. Internet provider also knows how to relate this ip with the individual.

To get around ip stuff, deploying the solution on Tor might be an option.

**Comment by pascalwhoop** [comment]
By the time we find a perfect system that everyone will be perfectly anonymous it will be either 
- useless 
- 3 years too late
- so complicated to use that no one will use it 

I think this applies to a lot of issues raised. The whole white paper already outlines so much that makes the users 1000x more anonymous than anything that came before it. But if we discuss until 2022 how we can make it more anonymous, we may as well drop the goal of fighting covid19 with this

**Comment by jorants** [comment]
Maybe you should?
The project often seems to be focused on being more secure then other approaches, while the question should be whether it is secure to a certain standard. Looking at it, and systems like this in general, it might be unavoidable that this will become a huge invasion of privacy.

**Comment by lbarman** [comment]
Thank you all for your inputs. IP's are not a long-term stable identifiers but definitely reveal information about your location, and I think are considered PIIs. As @pascalwhoop said, we feel that anonymous networks are neither scalable enough, nor exactly needed with our approach (see FAQ  [P5](https://github.com/DP-3T/documents/blob/master/FAQ.md#p5-why-not-use-mixnets-or-other-anonymous-communication-systems-to-query-the-server)).
