### ISSUE TITLE
Clarify CDN usage

### ISSUE THREAD

**Issue by jeffallen** [DP-3T/documents#55]
In the scalability section of the white paper, the possibility of using a CDN to distribute the infected users lists was mentioned. Good! It would be helpful to get quite explicit here, saying, "there can be one URL per day, and the contents will be static, with a size of X, so this content will be easily catchable and easily distributed from a CDN".

I mention this because in section "Decentralised proximity tracing", above "scalability", there is the sentence "Periodically, the backend sends the Set of infected patients...", to which I wrote in big letters, "WHY PUSH? WHY NOT CDN!?!"

**Comment by kennypaterson** [comment]
Thanks. We are actively investigating the capabilities of CDN providers, along with associated privacy and security risks.
