### ISSUE TITLE
Please clarify usage of AES in counter mode

### ISSUE THREAD

**Issue by jaromil** [DP-3T/documents#57]
The use of AES on top of HMAC It is not clear from the whitepaper: it is briefly said that a PRF is derived from the HMAC and fed into a PRG based on AES used in counter-mode. But the use of AES is not very explicit and I'm insecure about my own implementation, perhaps this is better explained with an example: 

Here I'm using AES-GCM with aead, which basically takes 4 parameters:
1. the secret key
2. the plaintext
3. the IV (counter)
4. the header (to be authenticated)

```lua
for i=moments, i<0, i--
  iv = SHA256:process(tostring(i*1000000)) -- IV = counter * 1000000
  PRF = SHA256:hmac(ACK.secret_day_key, BROADCAST_KEY)
  PRG, checksum = ECDH.aead_encrypt(PRF, PRF, iv, BROADCAST_KEY)
done
```

and in my current prototype I'm using the 16-byte long checksum as EphID, but I suspect this is wrong. In case I should use a 16 byte portion of the PRG (ciphertext) as EphID, then what do you suggest is used as plaintext and IV, considering they cannot be random as determinism is needed? And is the authenticated header really needed then? (perhaps useful to authenticate the broadcast key?)

**Comment by kennypaterson** [comment]
AES-CTR is used to generate a sequence of pseudo-random bytes. This is done by using the HMAC output as a key for AES and running AES in CTR mode starting from 0^128 as the initial counter. Then you split the output stream of bytes up into ephemeral IDs. You don't need AES-GCM.

**Comment by snakehand** [comment]
How is the IV / nonce derived for AES-CTR ?

**Comment by kennypaterson** [comment]
Set it to 0^128 (all zero bit string).

**Comment by jaromil** [comment]
Would you mind being more explicit about the input plaintext?

AES-CTR takes three arguments:
- a key (the PRF)
- a plain-text (the 16 byte long counter)
- a nonce (16 zero bytes)

**Comment by kennypaterson** [comment]
We are running AES-CTR more as a PRG, not as an encryption mechanism. So we really only care about the "raw" AES output blocks, obtained as AES(K,ctr) where ctr is a counter starting from 0^128. So there is no plaintext here.

**Comment by dirkx** [comment]
So just to confirm - SHA256:process(tostring(i*1000000))  in this example gives us for i = 2 the string value "2000000". And we SHA256 exactly that without any \0; so the result be:

    echo -n 2000000 | openssl sha256
    (stdin)= dd80d7a873341d491936c851964a9793195f37e646f6809dd546e2946f46d283

And for n=10 we'd SHA256 a byte sequence which is one byte longer. Correct ?

And - not knowing rust - fair to assume that:

     PRF = SHA256:hmac(ACK.secret_day_key, BROADCAST_KEY)

is to be read as password, payload. So for a secret_day_key that is 32 bytes set to 0 we'd get 4d91fd2e6c3b27ed696d9a2c971cd148da9d6e13a95749e140d37c3087053ea1 if the BROADCAST_KEY was b"Decentralized Privacy-Preserving Proximity Tracing" (again without any terminating \0.

  PRG, checksum = ECDH.aead_encrypt(PRF, PRF, iv, BROADCAST_KEY)

with the first argument what is normally known as the key in AES (16, 24 or 32 bytes), the second argument is the plain-text in, the 3rd argument is the 'IV" and the broadcast key is here used for the header/integrity checksum ??

**Comment by jaromil** [comment]
Hi @dirkx ! my code above is obsolete. I will update the pseudo code in issue #62

**Comment by dirkx** [comment]
yes please - want to get a testcase of apple primitives and openssl primitives output the right test vectors :)
