### ISSUE TITLE
Is just sharing contacts enough? better sharing contacts of contacts.

### ISSUE THREAD

**Issue by diedicar** [DP-3T/documents#59]
The purpose of the tracing app should be provide information to agents ahead of the spread of the virus. Keeping just record of personal contacts is likely to be too slow. Clients should be able to understand their probability of contagion and self insulate or just manage their risk. Presently I can be alerted only if one of my contacts gets sick, with this improvement I'm going to be alerted before he knows it. 
The privacy oriented design will be a definitve plus just if we don not sacrifice the speed of the signal, which can be done without involving the central server. Clients will simply transmit  to the server only their identifier when infected and not infected clients will calculate their probability of contagion locally as before.

In terms of storage requirments we'll need the square of the memory necessary in the present design which seems me affordable (some dozens of megabyte/ months, if i get it correctly)

In order to obfuscate the true social graph clients could send fake second order contacts together with the real ones.

Which are the drawbacks to this expanded solution?

**Comment by kennypaterson** [comment]
Thanks for sharing this idea. We invite you to develop it further, paying close attention to the cost of such a solution and the utility benefit that it would bring. It is too far from the current proposal we have, and the timeline we envisage for releasing a working a system, that we can consider it in detail ourselves.
