### ISSUE TITLE
Using a blockchain for backend servers

### ISSUE THREAD

**Issue by jatorrero** [DP-3T/documents#6]
I think that for backend servers you could use a smart contacts in a blockchain with ZKP (Zero known proof)

The app would be a blockchain wallet that makes transactions with other apps, and in the transaction the app knows if the other user is infected.

**Comment by Selinde** [comment]
I do not think using blockchain is a good idea here. Blockchain is only useful if you do not have a central party that you trust to not alter the data. At the same time, blockchain has many downsides that a central database would not have, amongst which higher complexity and possible scalability issues.

**Comment by jatorrero** [comment]
No, if you use permissioned and  not proof of work blockchain. These kind of networks can scale, and the complexity is lower. Here in Spain we have a national blockchain network using that uses quorum and hyperledger. The EU is also creating a European-wide blockchain.  And if you want to extend this solution to many countries, in what central authority you trust?

**Comment by Selinde** [comment]
If you have a permissions blockchain and, for example, proof of authority, you still need to trust the organisations that are nodes in the network. If I understand the design in the white paper correctly (but correct me if I am wrong), there is a central system for each country that uses the system and if someone has been in several countries, they can use each of their databases.

I do not see a reason for e.g., national authorities to alter the data stored centrally. Why would they do this?

The question remains what benefits blockchain offers in this case that makes the additional complexity and possible difficulty with implementation defendable.

**Comment by kennypaterson** [comment]
Thanks for this comment. We have considered and decided not to adopt any blockchain technologies or ZK proofs in our approach. We do not see a role for blockchains, nor ZK proofs; using the latter in any significant way would also slow down our development.
