### ISSUE TITLE
Proposal to ensure anonymity after infection

### ISSUE THREAD

**Issue by leukipp** [DP-3T/documents#60]
Here a proposal, which could improve de-anonymization of infected individuals (#37, #24 ), fake contact events (#35) and also the problem of a malicious attack by increased broadcast range.

Setup uses the existing **SK​**, **EphID​​** (same functionality, indices ignored here) with an extra pair:
- **PK** is generated like **SK**.
- **ConID** is generated during contact.

Contact phase:
1. *A* sends **EphID​_A** broadcast.
2. *B* receives **EphID​_A** and generates something like **ConID​_B=f(EphID​_A) + h(PK_B, EphID​_A)**, where **+** := { string concatenation, **f** := { hashing function, **h** := { hashing function.
3. *B* sends **ConID​_B** broadcast.
4. *A* receives and stores **ConID​_B** if it's the response to (1.). e.g. **ConID​_B** starts with **f(EphID​_A)**
5. Same procedure in the other direction and with multiple devices.

What *A* now knows:
| EphID | ConID​ |
|--|--|
| EphID​_A | ConID​_B = f(EphID​_A) + h(**X**, EphID​_A) |
| EphID​_A | ConID​... |

Infection phase:
 - *B* has a confirmed infection and is approved for server transmission.
 - *B* uploads his **PK_B** key and all clients fetch the list of infected keys.
 - *A* checks locally for every **EphID​_A** if there is a **ConID​** match with **X = PK_B**.
 
 The process is almost the same as in the Whitepaper, with some advantages:
 - With **PK** you are not able to generate **EphID**.
 - Faking valid **ConID** entries always needs access to two devices.
 - Broadcasts with a range increase on the transmission side will not work, since you wouldn't be able to receive the hashed response.
 
 Possible pitfalls:
  - I'm not a cryptography specialist, maybe this just shifts the de-anonymization gateways to some other place.
  - There could be some intrinsic Bluetooth limitations for this approach.
  - ... your comments against this implementation.

**Comment by jasisz** [comment]
I believe this is very close to the closed https://github.com/DP-3T/documents/issues/35

**Comment by inaitana** [comment]
Also, it looks like any solution involving handshakes is ruled out due to unreliability of the Bluetooth advertising medium.

Besides, I see why this would avoid fake contacts and mitigate increased range attacks (since the attacker wouldn't get the step 2 "ack"), but I can't figure out why this would mitigate #37 in the abscence of range increasing.
If A is a malicious wardriver, he would actually have met B (and recorded his location), so he would have the corresponding ConID_B, and would be able to check PK_B against it.

**Comment by leukipp** [comment]
> I believe this is very close to the closed #35

Yeah, but without bandwidth increasement, since only **PK** gets published and not the hashed ConID list.

**Comment by leukipp** [comment]
> Also, it looks like any solution involving handshakes is ruled out due to unreliability of the Bluetooth advertising medium.

Could you explain this further?
Thinking about that leads me to the conclusion that the overall traffic in a room with N devices would dramatically increase up to N + N * (N - 1) = N<sup>2</sup>. 

> Besides, I see why this would avoid fake contacts and mitigate increased range attacks (since the attacker wouldn't get the step 2 "ack"), but I can't figure out why this would mitigate #37 in the abscence of range increasing.

I think without range increase you would not be that successful in collecting personalized data, but if you come close enough to get a valid ConID you would be glad to get a notification in case of infection.

The easier way for such an attack would be to place a device with a camera in a high frequented area.

**Comment by inaitana** [comment]
> Could you explain this further?
> Thinking about that leads me to the conclusion that the overall traffic in a room with N devices would dramatically increase up to N + N * (N - 1) = N2.

Yes this appears to be the reason, as explained in the [FAQs](
https://github.com/DP-3T/documents/blob/master/FAQ.md#p4-why-is-the-system-not-using-public-key-cryptography-when-broadcasting-identifiers).

> I think without range increase you would not be that successful in collecting personalized data, but if you come close enough to get a valid ConID you would be glad to get a notification in case of infection.
> The easier way for such an attack would be to place a device with a camera in a high frequented area.

BLE range is not that low. I don't know which tx power is likely to be used (also to grant cross compatibility), but the scenario I described in #37 (walking or slowly driving in front of homes) would probably collect a lot of broadcasts even with low power.

**Comment by leukipp** [comment]
The quadratic increase is a valid reason against this implementation.
