### ISSUE TITLE
Jumping LatLon

### ISSUE THREAD

**Issue by obi458** [DP-3T/documents#65]
For smaller downloads, use jumping latitude and longitude, JLL.
Currently the users have to download the seeds of the whole world, which could be a lot!
Remember: Bluetooth Low Energy (BLE) scanning will only work if Location services are enabled on the device!!

**How to:**

The first time the apps starts, the JLL are calculated, **once**.
The JLL is a 32 bytes number. 
We can broadcast this using **Major and Minor** of the Beacon protocol, which are not using yet,
Major and Minor are 16 bytes number.

The infected person upload the seed and the JLL, {JLL,seed}. 
To download the seeds, the backend server use this JLL to filter the seeds, which are in contact to the downloading person. 
This minimise the seeds to download and minimise the calculation the client has to do.
No seeds or other ids of the client are necessary.

For example the client use: select seed from seeds where JLL in [ListOfMYJLLs]

How to calculate the JLL:

m = 10^6, P = 2^32
Longitude, Latitude as decimal number

JLL = (Latitude * Longitude * m^2) mod P.
Major is the high 16 bytes, Minor is the low 16 bytes.

JLL are squares with about 380*380m^2.

The mod function makes, that, for example:
Munich - Maximilian street, New York - Timessquare, Singapure - Orchard Road have **the same JLL**.
Therefore the real location is hidden and can not calculated back.

Further if a cluster of infection is build anywhere in the word the number of seeds explode and the number of downloads too, which JLLs this will not!

**Comment by kennypaterson** [comment]
Thanks for this suggestion. We have considered, and will continue to consider, various "sharding" solutions to deal with scaling challenges. However, we will not use location data in our solution, as we consider it to be too privacy-invasive. Note that your solution might give the same "coding" to 3 distinct areas, two of which are in the middle of the ocean, and so rather unlikely to the location for users of the system, so it does not in reality hide location information.
