### ISSUE TITLE
Deanonymizing EphID handling

### ISSUE THREAD

**Issue by kreativmonkey** [DP-3T/documents#67]
On this point the system is also vulnerable. If a malicious client logs the EphID and timestamp or, as described in the paper, distributes beacons, the attacker can trace each EphID back to exactly one person. He only needs one EphID in the time period that is not anonymous and even gets a motion profile. This is the reason why we have rejected this approach for the time being.

How do you see this attack scenario?

_Originally posted by @kreativmonkey in https://github.com/DP-3T/documents/issues/21#issuecomment-609051085_

**Comment by lbarman** [comment]
Hi @kreativmonkey; thanks for the input. I'm not 100% I get everything, this sound similar to what is described in the 1st paragraph of page 25 of the white paper. Could you contrast it with that text ?

>  He only needs one EphID in the time period that is not anonymous and even gets a motion profile.

Could you detail this ? Does this assumes that the adversary knows how to group EphIDs per person (e.g., by constant monitoring) ?
Thanks
