### ISSUE TITLE
Bluetooth iOS implementation challenges

### ISSUE THREAD

**Issue by gajeam** [DP-3T/documents#7]
I absolutely love this design. I just wanted to bring up a couple implementation challenges that this might face on iOS, specifically with regard to Bluetooth Low Energy (BLE).

Apple places limitations on how frequently an iOS app can send out BLE signals while it is in the background. In general, the iOS operating system is very stingy about allowing apps to perform activity in the background. If an app tries to do too much, the system will allow it to wake up less and will eventually cut it off entirely. With Bluetooth, apps can mitigate this somewhat by decreasing how often they send signals out, but as Apple says in their documentation, [it can't run forever.](https://developer.apple.com/library/archive/documentation/NetworkingInternetWeb/Conceptual/CoreBluetooth_concepts/CoreBluetoothBackgroundProcessingForIOSApps/PerformingTasksWhileYourAppIsInTheBackground.html#//apple_ref/doc/uid/TP40013257-CH7-SW1) To make sure that the application is still sending out the Bluetooth signal, **designers may want to ask users to open the application before they leave the house.** This would also ensure that the app has loaded more EphIDs and does not put it at risk from being punished by the operating system for doing too much in the background.

However, there may be a more fundamental challenge to this design on iOS. According to Apple documentation, it looks like an **iOS app that is sending a Bluetooth signal while in the background cannot connect to an iOS app that is listening for a Bluetooth signal while also i the background.** I have not tested this myself but this [StackOverflow answer](https://stackoverflow.com/a/20460113/1031615) suggests the same thing. Apps scanning in the background can only scan for specific UUIDs (here the UUID would represent the app itself, not the EphID) and apps sending BLE data in the background can only send their UUID in what Apple calls a ["special 'overflow' area"](https://developer.apple.com/library/archive/documentation/NetworkingInternetWeb/Conceptual/CoreBluetooth_concepts/CoreBluetoothBackgroundProcessingForIOSApps/PerformingTasksWhileYourAppIsInTheBackground.html#//apple_ref/doc/uid/TP40013257-CH7-SW1) that I am fairly sure would not be recognizable to the device as a UUID.

Again, I have not been able to test this myself yet so I am not totally sure this is correct. I would love to hear from other iOS developers on this issue, or even better, see what code you all have coming down the pipeline. Outside of GitHub, you can find me at [@GabeNicholas](https://twitter.com/gabenicholas).

**Comment by misterinterrupt** [comment]
https://developer.apple.com/documentation/usernotifications/setting_up_a_remote_notification_server/pushing_background_updates_to_your_app

**Comment by ckrey** [comment]
I did a bit of reading and an Prove-of-Concept implementation based on "CoreBluetooth" on iOS/MacCatalyst:

Result as expected above:
In Background, iOS does not advertise localName, nor specifically set ServiceUUIDs. Thus it cannot be be detected by an iOS App scanning in Background.

Works well in foreground. 

[dp-3t-ios.tar.gz](https://github.com/DP-3T/documents/files/4433202/dp-3t-ios.tar.gz)

**Comment by gajeam** [comment]
Per @misterinterrupt's comment about the first concern —
Apps can only send background push notifications [two or three times an hour](https://developer.apple.com/documentation/usernotifications/setting_up_a_remote_notification_server/pushing_background_updates_to_your_app) and even then it only wakes the app up for thirty seconds. Otherwise again, Apple will punish the app and let it wake up less often in the future.

**Comment by YousefED** [comment]
This approach by a related app (covid-watch) might be relevant: https://github.com/covid19risk/covidwatch-ios#covidwatch-ios.

**Comment by kennypaterson** [comment]
Thanks, we are aware of the BLE challenges especially on iOS and are working to resolve them as best we can.
