### ISSUE TITLE
Traffic Light Syndrome

### ISSUE THREAD

**Issue by mrseeker** [DP-3T/documents#70]
This is a bit related to #19 but then on a different scale. What if you use the app as a way to only allow "non-infected" people in your establishment? Similar to the way they do it in China, but then completely anonymized.

The whitepaper states that there are 3 states:
- Non-infected (Green Stage)
- At-Risk (Yellow Stage)
- Positive (Red Stage)

Since the app is completely anonymous, it relies on the "arbitrator" (in this case the public database of infected people) to tell who is in the Red Stage. Anyone who has been in contact with this person is considered "at risk" and will receive a Yellow Stage alert. All the rest are green.

What if this is linked to "showing" your app before allowing someone entry? Let's say that everyone who is not in the green stage needs to stay at home. What will happen is that you only need to deny entry to everyone on the "blacklist" (aka Red Stage) and their "accomplices" (Yellow Stage). This can be done without any involvement from the government, since the app will do all the calculations for you. It's completely anonymous since it coheres to the whitepaper.

Now, someone who is "tech savvy" will most likely try to do 2 things: Either "trick" the app by not downloading any data or remove any data from the database as soon as they are being at-risk. To prevent this from happening, you most likely need to make sure that the person who is being checked does not "game" the system. You can do that in 2 ways: Either by making sure that the database needs to be fully loaded before receiving "green" access, or making sure that they checked themselves using the latest database. All those things can be done client-side, and do not require any relationship with the server. You only identify yourself to someone else using the same system as normal, prove to the other person that you are a valid "Green" person and that your "ID" is not revoked in any way before you are granted access.

This method is similar to the way they did testing in the middle ages: When you wanted to get out of a city, you got a stamp from the local municipality stating that you did not have the plague. That stamp ensured you that you could go to the next city, which issued another stamp on top of the previous one. If you happened to be visiting a city that had a case of the plague, they simply refused you based on your travel history. Just the fact that you had a stamp from that region was enough to deny you entry. Someone without any history would also be affected since they would immediately be denied entry, and had to sit in quarantine and be inspected by plague doctors before granting access (and receiving a stamp when leaving). This way they ensured that the plague would not spread from town to town.

**Comment by bdsl** [comment]
Why wouldn't someone who is tech savy be able to trick the person at the door by showing them a fake app?

Or installing the app on a phone that they keep in quarantine, and only take out when they want to show it to someone?

The Alipay app in use in China doesn't just show a green light - it shows a green QR code. I expect that's linked to personal details that can be checked on a central database.

**Comment by bdsl** [comment]
Client side code in general can only be trusted by the person physically holding the client (and by extension by people that trust that person), since no-one else knows whether they've replaced it with code that they prefer.

**Comment by mrseeker** [comment]
You have something called the "safetyNet assestation" in Google, which purely signs the APK and confirms that you have the correct app. This can be used to validate if the user is indeed holding an official app and not a "replacement". Think bank-grade security here, the same that banks use for payments. You don't need to push any medical-related material here, just a random token that verifies that the app you are holding is indeed valid.

**Comment by mrseeker** [comment]
I used "green light" as a metaphor, but you can change it into anything you like, like a green QR code with a token that validates that the owner of the device is indeed holding a valid app (by giving it a nonce + signed token).

**Comment by BK024** [comment]
> 
> 
> Why wouldn't someone who is tech savy be able to trick the person at the door by showing them a fake app?
> 
> Or installing the app on a phone that they keep in quarantine, and only take out when they want to show it to someone?
> 
> The Alipay app in use in China doesn't just show a green light - it shows a green QR code. I expect that's linked to personal details that can be checked on a central database.

I feel bdsl mentioned a more important point here, that was not answered. Forget 'tech savvy', what stops anybody from taking an old phone from a drawer, install the app and only use that phone if they want to appear 'green'?

Using the app in the way described in the original post in this thread seems therefore unviable to me. Also unwanted, but that is a personal point of view and therefore not part of this discussion (I think?).

**Comment by s-chtl** [comment]
Hi all, thank you for your inputs (and apologies for the response delay). Indeed, such a behaviour could occur but it might be out of the scope of this project as it is more an extension of what users could do with the functionality of the App (as was #19 ). It is not our primary objective to provide a "traffic light" system but more to deliver some information only to the users. 
I'll close this thread for now if that is ok with you.
