### ISSUE TITLE
Better/solidly define the Eph_id generator

### ISSUE THREAD

**Issue by dirkx** [DP-3T/documents#71]
Right now the Eph_Id generator is defined as

EphID​ || ... || EphID​ = PRG( PRF(SK​ , “broadcast key”) )

with some options for the PGR (AES in counter mode, or Salsa20) and one optin for the PRF (HMAC_SHA256). And the exact introduction of the N into this; and the 16 bytes extract is not specified.

May be good to define this better - as the current 3 proposals are all subtly different (stringified day-counter x 1000 as the IV, ECHDA or AES, day-counter as the plaintext).

**Comment by snakehand** [comment]
Closed Issue #57 sheds some light on this.

**Comment by dirkx** [comment]
Actually - that one was out of date as well -  #62 is now the right place to be.

**Comment by kennypaterson** [comment]
Closing this issue, as it is being addressed elsewhere.
