### ISSUE TITLE
What is the security level of PRG( PRF( SKt, "broadcast key") )?

### ISSUE THREAD

**Issue by tree-go** [DP-3T/documents#72]
Is there any reference (how to prove) for the security strength to use AES-CTR(HMAC-SHA256(SKt, "broadcast key"))?it is seems not the simplest PRG(SKt, i)

**Comment by snakehand** [comment]
There might be performance consideration here. You can set up the AES key once, and repeatedly encrypt different input blocks with the same key to get multiple ephemeral IDs.

**Comment by kennypaterson** [comment]
This can be analysed using standard results on HMAC's security as a PRF plus AES's security as a PRP (and using the PRP-PRF switching lemma). The analysis requires two game hops; first switch the HMAC output from real to random, using PRF security of HMAC. This makes the AES key uniformly random. Second, use AES's PRP security and the PRP-PRF switching lemma to change the outputs from AES to truly random strings. In the end one obtains a bound on any distinguisher trying to distinguish the output sequence from random that is a sum of terms relating to PRF security of HMAC, PRP security of AES. and a term of the form q^2/2^n where q is the number of outputs used from AES (that comes form the PRP-PRF switching lemma); q = n/16. The analysis is standard.
