### ISSUE TITLE
Bluetooth Distance assumption

### ISSUE THREAD

**Issue by noci2012** [DP-3T/documents#73]
There seems to be an assumption on the limited distance to observe BT devices.
(<10m for 2 way communication) just scanning possible damaged data a bit ore, 50-100m scanning for BLE (from the document).

While in the past BT access has been accomplished using very simple items. (2005)
So picking up Communication possibly combined with a camera (not to hard to add) how can this be called private data?

Increasing the range is not too hard to do: up to 2Km for pairing ==> communication 2 ways.
The most expensive part probably would be a tele-lens if a camera is mounted.

Original articles were not available anymore, so archive.org replacements are given.
ref:
https://www.schneier.com/blog/archives/2005/04/bluetooth_snipe.html
https://web.archive.org/web/20050129094007/http://www.pentest.co.uk/documents/bt_dongle_mod/bt_dongle_mod.html
https://web.archive.org/web/20050915030814/http://www.tomsnetworking.com/Sections-article106.php
https://web.archive.org/web/20050815004733/http://www.tomsnetworking.com/Sections-article135.php
https://web.archive.org/web/20050225100005/http://wifi-toys.com/wi-fi.php?a=articles&id=21

**Comment by nicorikken** [comment]
So to rephrase: you propose an attack vector where emphIDs are recorded together with personal information, in this case photos, so the identity of infected person's can be revieled once the emphIDs have been published. Right?

**Comment by noci2012** [comment]
Not necessarily infected people.   Just sniff data from longer than expected disances, also spread data over longer distances.
It can also be used to project sniffed (long distance pickup at least in a 1.5Km radius)  and then spread those around again  causing many more meetings than actually have been. 

ie. it can be used to feed false info into the system on a fairly large scale. 
Needed some wifi stick + yagi antenna.

So care must be taken with relevance of data.


If i read the specs right then there is a random BT macaddress sent ONLY with beacon frames. 
For all other packets the real MAC address is used. So identification beyond the scope of Covid is also possible,.

**Comment by lbarman** [comment]
Hi @noci2012, sorry for the delay. For the risk aspect, I think this has been raised a few times (e.g., your attack is a long-range attack of https://github.com/DP-3T/documents/issues/121 if I get it correctly). 
As for the distance, malicious users can send/receive over longer distances, this is true. 
> So care must be taken with relevance of data.

Absolutely. The Bluetooth part of CT is still being worked upon, but we are aware of these risks. Cross-referencing in https://github.com/DP-3T/documents/issues/188
Would this answer the question? Happy to discuss more if you have further inputs.
