### ISSUE TITLE
Excretion period starts n days before first symptoms

### ISSUE THREAD

**Issue by alixMougenot** [DP-3T/documents#76]
The period of excretion (the period during which one can contaminate) for a patient with covid19 starts up to n days before the first symptoms. n is typically less than 14 days as of most recent publications.
The server that will publish the PK for positive individuals needs PK(t-n) where t is the date of first symptoms and n is the shift between the first symptoms and the beginning of the excretion period. This is not clearly explained in the white paper.

**Proposed Solution 1:**
Write that t is t-n. Where n is a parameter. Thus, the App must keep a history of generated PKs for a period that starts before the first symptoms.

**Proposed solution 2:**
You can also solve this by making the keys predictable from present to the past, instead of from present to the future. If you make the PK generation like this:
```
PK_t-1 = H( PK_t )
```
Knowing the PK of the first symptoms is now enough to cover the past of that individual, but not the future. By recursively applying H.
The App upon choosing PK; can compute and store the series of PKs for the entire 2 years to come. And there is no need for selecting a new seed PK after publishing PK(t).

**Comment by diedicar** [comment]
There is also mounting evidence that asymptomatics are definitely infective. Th researchers of Italy' s Vo Euganeo study emphasize this point.

**Comment by alixMougenot** [comment]
This issue is solved in the latest version, the document now mentions the first day of being contagious instead of first symptoms.
