### ISSUE TITLE
TRUNCATE128 missing on p13

### ISSUE THREAD

**Issue by defeo** [DP-3T/documents#77]
On p13, it is said that

```
TRUNCATE128( H( H( seed​ t​ ) || t) )
```

is inserted in the Cuckoo filter, however I guess the intention was to put

```
TRUNCATE128( H( TRUNCATE128 ( H( seed​ t​ ) ) || t) ) 
```

(not sure about the outermost `TRUNCATE128`)

**Comment by cascremers** [comment]
This is a typo -- we will fix this asap. It should be:
```
H( TRUNCATE128( H( seed​_t​ ) ) || t ) 
```
I.e., it is the hashed identity `H(EphID || t)` where `EphID` = ` TRUNCATE128( H( seed​_t​ ) ) `) .

**Comment by defeo** [comment]
You're welcome.

**Comment by cascremers** [comment]
Thank you!

**Comment by dirkx** [comment]
thanks !

**Comment by cascremers** [comment]
This is fixed now in the new version of the whitepaper, thanks!

Closing this issue as fixed.

**Comment by dirkx** [comment]
Thank you !
