### ISSUE TITLE
Malicious (modifying) backend could possibly easily create fake risk events(?)

### ISSUE THREAD

**Issue by sk13** [DP-3T/documents#78]
Regarding the protocol version which uses the Cuckoo filter I wonder if a modifying backend server could easily generate fake contact evens by manipulating the content of the Cuckoo filter.
[Just to illustrate: If it would not be a Cuckoo filter but a simple Bloom filter the malicious backend would just need to set all bits to ‘1’ – depending how the Cuckoo filter is dimensioned similar attacks should be possible.]
(Note that in principle a modifying backend server could also sent out fake seeds -- but it seems that the likelihood of creating a collision is acceptable low).
If such an attack is possible I wonder if one could at least detect malicious backends (maybe with the help of some traps…)

**Comment by lbarman** [comment]
Hi @sk13, thanks for your input! 

Indeed a malicious backend could do as you describe. In short, it is outside of our threat model:
> This backend server is trusted to not add or remove information shared by the users and to be available. However, it is untrusted with regards to privacy (i.e., collecting and processing of personal data).

(Whitepaper page 9)

The rational behind this is that the backend will likely be maintained by some authority, which would be held accountable if they performed such (fairly visible) attack. 

(I'm not sure how you would design "traps" to run in client code which hackers have access to)

Would this answer the question ?
