### ISSUE TITLE
Involve Google -> Use existing Maps history functionality

### ISSUE THREAD

**Issue by amalic** [DP-3T/documents#8]
I would find it much smarter if we could get Google involved. 

Here's my idea:
1.) Google could push out a message to iPhone and Android users of Google Maps, asking them to enable their location history or add a special function that only stores the last 3 weeks and is not used for anything else but contact tracing
2.) Google could enable in the Account page a function where people can report that they got infected, and inform others who were in the same area at the same time, and that they might be at risk to be infected too

In my opinion Google could act as so called Trusted Third Party. It only has to be clear that European data does not leave the continent. The rest can be done through everybody's consent.

License: CC BY 4.0

**Comment by aral** [comment]
Is this because Palantir is unavailable?

**Comment by amalic** [comment]
Funny ;) Palantir's customers are not ordinary users but governments and intelligence services.

It's because Google has already a huge user base. Adding a temporary function to Maps would be easy to roll out. In Austria e.g. the contact tracing application of the Red Cross is being discussed to become mandatory because only 140k users have installed it so far on a voluntary basis. 

Google could enable local storage of movement data only. Devices could pull fully anonymized data of voluntary reports through automated or manual queries based on the local movement data and do all the necessary calculations on the device itself.

**Comment by jowouters** [comment]
Involving Google (or another commercial partner) is clearly not an option. 
In order to maximise acceptance, the solution:
- must be independent of a specific privately owned technology 
- can not enforce installation of additional commercial software (ex g maps)
- must be decentralised 
- must be completely open source

**Comment by amalic** [comment]
> must be completely open source

Looking through all three documents released in this repository I can only see this sentence
> _We are currently working on a reference implementation of the decentralized design which will be released openly during the next weeks._

This sentence above is so vague, that it can mean anything.

> G Maps does not offer that technology.

Same goes for those three documents. 

Google could easily add a function to Maps where users track their location history on their devices. Once someone got infected this location history could be upload fully anonymized and distributed to others. Such a service could be even hosted in an open infrastructure.

This could be achieved by first sending notifications about approximative locations to users. If someone's locally stored location history is within one of those approximative locations, the app could download the exact location history of someone who uploaded their data and compare it on the information stored on the device itself.

Another advantage would be that there is already a huge installation base, since basically every Android user has Google Maps, and most iOS users too. 

The fundamental problem is not about proximity tracing, but about enabling people to know if they have been in the same location as someone who was infected. Proximity tracing is just a solution that has been crafted in those documents.

Another issue with the idea of this application is, that it will require a centralized service which will enable users to upload their own tokens to some central service where theoretically billions of devices need to download every reported data set. 

Additionally, I think everybody here is massively underestimating the effort to test such an application on thousands of different device types, and the infrastructure requirements to host and run such an application. 

License: CC BY 4.0

Here is the Application from the Austrian Red Cross which (German only) which is already doing basically the same as the idea in those three documents. It's also openly available.
https://www.roteskreuz.at/site/faq-app-stopp-corona/

**Comment by kennypaterson** [comment]
Thanks for this discussion. Using location data is something we have striven to avoid in our proximity-based design. We are aware of the scaling issues in our (and other) designs. We believe that as a team, we have expertise and contacts to help us address these.

**Comment by amalic** [comment]
Seen this?

Apple Blog: [Apple and Google partner on COVID-19 contact tracing technology](https://www.apple.com/newsroom/2020/04/apple-and-google-partner-on-covid-19-contact-tracing-technology/)

Google Blog: [Apple and Google partner on COVID-19 contact tracing technology](https://blog.google/inside-google/company-announcements/apple-and-google-partner-covid-19-contact-tracing-technology)

**Comment by arelaxend** [comment]
Google and Apple are probably the only one to master effectively the BLT technology. So, this is a good news, that they participate. Moreover, those two companies have leverage the possibility to use this protocol since they have been actively integrating BLT into our smartphones.
