### ISSUE TITLE
TEE on the backend for better privacy (if the TEE is private).

### ISSUE THREAD

**Issue by LefKok** [DP-3T/documents#81]
I find the new design that enables the redaction of identifiers really nice! However, it seems to lower the utility since the removed contacts are not considered for computing risk. 
I wanted to propose the design of a second backend that protects from the privacy leakage that infected users might suffer. The design is pretty simple. 

The infected users send all of their contacts to the backend, some labeled as sensitive.  This complete database can be accessed by a TEE.
The clients checking their risk by sending their contacts to the TEE which calculates locally their risk and sends them back a single bit (get_tested).

Two additional things need to happen in order to provide privacy for all users.
1) The TEE accesses the database via ORAM, this way the server does not learn the contacts of the clients.
2) The server publishes a commitment to the database which the client provides to the TEE together with the request. This way the server cannot detect the contacts of a single person by providing the TEE only with the IDs of that specific user and then seeing if the client gets tested.

There is still an attack where the client provides a subset of his contacts to the TEE in order to detect if someone is infected, but this seems to be applicable even if we implement a centralized ideal functionality.

**Comment by kennypaterson** [comment]
Thanks for this suggestion. We are avoiding the use of complex cryptographic constructs such as ORAM. Please see the FAQ.
