### ISSUE TITLE
Add mutations indicator to sent SK in case of infection. 

### ISSUE THREAD

**Issue by kkoenen** [DP-3T/documents#84]
Currently SARS-CoV-2 is in scope. By adding a mutation indicator to the uploaded SKt (i.e. SKtm), we can prepare for mutations. Maybe the compute risk step would be impacted?

By bringing the formulas for the risk computation to the backend, complex and unforseen changes can be modeled without a need to update the app. For instance, the location (temperature, humidity, even air pressure?) of the computing client might turn out to be relevant for evaluating infection risk based on SKt pushed. Thresholds might vary from country to country. 

Alternatively, the app can hold the risk compute formulas for each mutation and check for updates of those formulas when new SKt is broadcasted.

**Comment by s-chtl** [comment]
Hi @kkoenen, thank you for you input. We are discussing with epidemiologists actively to match their needs. Additionally, having the risk computed by the backend may induce privacy issues. The last solution you mention might be the most promising. 
I'm closing this for now until we have more information.
Thanks
