### ISSUE TITLE
Allow users in high risk state to publish their SK (notify contacts of contacts)

### ISSUE THREAD

**Issue by diedicar** [DP-3T/documents#86]
(depending on issue #85 )Definition of risk, effectiveness of tracing, speed of the outbreak, may in every moment change and require to enlarge the radius of notifications to second> nth degree contacts,  

EDIT: as pointed out in issue #160 knowing that contacts are in high risk state can also suggest a transmission happening via fomites and give the alert.

Users which are in high risk status could upload data as the positives. As a pre-requirement they have to be able to prove their high risk status to the backend or other authorities. This proof is the analogous of swabbing done in an electronic manner, hence mimics  the original design based on sequences of voluntary disclosures.

See #85 for a protocol that guarantees to keep the backend unaware of social graphs since the high risk contacts will not disclose the infected they are linked to.

**Comment by lbarman** [comment]
Hi @diedicar, also closing this one as this would be a extension of #85 and not of our own system. As I said, you suggestion in #85 is interesting but is not aligned with our immediate goals. Thanks for your understanding :)

Continuing the discussions of "notifying contacts of contacts", which would be an extension of our own system, on #160 ...
