### ISSUE TITLE
Clarify roaming behavior

### ISSUE THREAD

**Issue by kugelfish42** [DP-3T/documents#88]
It seems that backend only distributed infected IDs for their own administrative domain and that mobiles should use their location to contact the relevant backend(s?) for the IDs.

If two users meet closely in a third domain and then return home where one is tested positive. How would the other one be alerted?

**Comment by mex2meou** [comment]
Hi @kugelfish42, thanks for the question!

An infected user would upload its (SK_t, t) (assuming the low cost design) pair to the backend service of every country he/she visited. Moreover,  roaming users would request the (SK_t, t) pairs of infected users from all the backend services that are responsible for the countries they have visited recently.

Please, note that we are currently working on the details of roaming and there will be further descriptions about it in future versions of the whitepaper.

**Comment by lbarman** [comment]
This will depend on https://github.com/DP-3T/documents/issues/68, let's move the discussion there :)
