### ISSUE TITLE
Motion detection to modulate tx power

### ISSUE THREAD

**Issue by inaitana** [DP-3T/documents#89]
Would it be a good idea to monitor (or maybe sample) motion and gyroscope sensors to detect if the device is lying still on a surface, and further decrease tx power (and/or rssi detection sensitivity) accordingly?

This would likely happen when the user is at home or in his workplace, and could mitigate risk of being detected from outside.

As far as I can see, these might be the pros:

- Mitigating frequent locations tracking of infected users. Even with design 2, eavesdroppers might observe a high number of positives for EphIDs tracked close to a home or a workplace.

- Mitigating single EphIDs tracking. An (anonymous) EphID's movements can be tracked with any design during a single day, and then linked to his home or workplace.

- If the device is laying still, there's probably less broadcast noise around it. Rationale being one wouldn't leave his device unattended in a crowded room. Also, contacts are likely to be at closer range and last longer then in a casual environment. A lower power might be sufficient to detect contacts.

- If the user left the device in another room of his home/workplace, there's no real point in trying to trace contacts seen in other rooms, as they might as well being seen in other floors or in the streets.

- Possible lower battery usage due to lower tx power.

And these could be the cons:

- The contact tracing precision would still be lower. If the tracing aggressiveness should desirably be high, at the risk of false positives to avoid false negatives, then this might be a regression.

- Possible higher battery usage due to sensors polling.

- Possible compatibility issues with different manufacturers, sensors and operating systems.

**Comment by lbarman** [comment]
Hi @inaitana, thanks for the long input ! Sounds like a good idea, our Bluetooth team is aware of it.
> Mitigating frequent locations tracking of infected users. Even with design 2, eavesdroppers might observe a high number of positives for EphIDs tracked close to a home or a workplace.
> Mitigating single EphIDs tracking. An (anonymous) EphID's movements can be tracked with any design during a single day, and then linked to his home or workplace.

We have a new design with secret-sharing that also helps in this aspect, if you haven't seen.
Marking for closing to reduce the number of open issues; please don't hesitate if you have specific inputs for the Bluetooth team!
Thanks
