### ISSUE TITLE
Frame as adressing potential GDPR concerns

### ISSUE THREAD

**Issue by BierJess** [DP-3T/documents#92]
In terms of encouraging the adoption of these measures, politicians and policymakers will need a practical reason in order to take this on, so I would suggest framing this as soliving a “problem”they have: GDPR compliance. The GDPR is notoriously broad and vaguely worded and as such compliance is difficult, so if it’s possible to come to the respective governments with an approach that relives some of their concern, they are more likely to adopt it. I’m not a legal scholar myself, but Dutch universities have GDPR and data protection officers who might be helpful in terms of addressing the specific GDPR requirements that would be addressed by a decentralized approach. By explicitly adressing GDPR you can also make an argument for implementing this at an EU level thereby saving time by, in a best case scenario, potentially bypassing selective adoption in only some countries.

**Comment by veale** [comment]
Hi Jess,
I'm one of the coauthors, and a legal scholar. We have a [specific data protection document](https://github.com/DP-3T/documents/blob/master/DP3T%20-%20Data%20Protection%20and%20Security.pdf) analysing our system in terms of requirements and case law. Specific issues such as 'which lawful basis do you choose' will depend on national law and exact implementation approach.
Thanks

**Comment by BierJess** [comment]
Hi, I've seen that document. My recommendation was not a concern for GDPR compliance but rather a suggestion about how to position the paper so that it will be attractive to lawmakers, who need an explicit statment early on in terms of "what's in it for them."
