### ISSUE TITLE
Design 2 - loose ends in the white paper / tighten up the spec

### ISSUE THREAD

**Issue by dirkx** [DP-3T/documents#93]
Would be nice to specify for

      EphIDt = TRUNCATE128(H(seedt))

     Where H is a cryptographic hash function, and TRUNCATE128 truncates the output to 128 bits. 

that meant is; given the 32 byte seed, 256 bits; a H of SHA256; and that TRUNCATE means (for example) the first 128 bits (or an XOR of the first and last).

**Comment by mex2meou** [comment]
Hi @dirkx, thanks for the request! 

We will clarify this in the future versions of our docs.

**Comment by dirkx** [comment]
@mex2meou -- but for now -- which will it be; as in some countries implementation is already underway; and want to stay cross EU interoperable. Could you at least let us know which it will be.

As otherwise we'll have production implementations that use the first 128 bits of the 256 hash (i.e. literally truncate).

**Comment by kennypaterson** [comment]
@dirkx The problem (again :-) ) is that you are trying to implement from a whitepaper. We will have a reference implementation pretty soon, and this will clarify. For now, I suggest taking the least significant 128 bits, but be aware that you might need to switch it later to the most significant bits, and endianness may come into play. We will not be XORing halves together. Hope this helps - if not, then hit me up here again.

**Comment by dirkx** [comment]
@kennypaterson thanks - will do. And will also track this as the input for the EU recommendation paper 2020/4/16.

**Comment by dirkx** [comment]
Feel free to close this one if you feel that is right - then I mark it as 'done' design decision/confirmation on my end

**Comment by kennypaterson** [comment]
Thanks, it was already closed ;-)
